GRANT OWNERSHIP on TABLE MYDB_@ENV@_RAW.DATA_HUB.CONTACT to role MYDB_@ENV@_RAW__DATA_HUB__ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP on TABLE MYDB_@ENV@_RAW.DATA_HUB.ISSUE to role MYDB_@ENV@_RAW__DATA_HUB__ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP on TABLE MYDB_@ENV@_RAW.DATA_HUB.PUBLICATION to role MYDB_@ENV@_RAW__DATA_HUB__ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP on TABLE MYDB_@ENV@_RAW.DATA_HUB.PUBLISHER to role MYDB_@ENV@_RAW__DATA_HUB__ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP on TABLE MYDB_@ENV@_RAW.DATA_HUB.REF_FILE_FORMAT to role MYDB_@ENV@_RAW__DATA_HUB__ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP on TABLE MYDB_@ENV@_RAW.DATA_HUB.REF_INTERFACE to role MYDB_@ENV@_RAW__DATA_HUB__ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP on TABLE MYDB_@ENV@_RAW.DATA_HUB.REF_INTERVAL to role MYDB_@ENV@_RAW__DATA_HUB__ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP on TABLE MYDB_@ENV@_RAW.DATA_HUB.REF_METHOD to role MYDB_@ENV@_RAW__DATA_HUB__ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP on TABLE MYDB_@ENV@_RAW.DATA_HUB.REF_STATUS to role MYDB_@ENV@_RAW__DATA_HUB__ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP on TABLE MYDB_@ENV@_RAW.DATA_HUB.REF_STORAGE_METHOD to role MYDB_@ENV@_RAW__DATA_HUB__ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP on TABLE MYDB_@ENV@_RAW.DATA_HUB.REF_TRANSFER_METHOD to role MYDB_@ENV@_RAW__DATA_HUB__ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP on TABLE MYDB_@ENV@_RAW.DATA_HUB.REF_TRIGGER_TYPE to role MYDB_@ENV@_RAW__DATA_HUB__ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP on TABLE MYDB_@ENV@_RAW.DATA_HUB.SUBSCRIBER to role MYDB_@ENV@_RAW__DATA_HUB__ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP on TABLE MYDB_@ENV@_RAW.DATA_HUB.SUBSCRIPTION to role MYDB_@ENV@_RAW__DATA_HUB__ADMIN COPY CURRENT GRANTS;



