GRANT OWNERSHIP on TABLE ULTRA_@ENV@_RAW.DATA_HUB.CONTACT to role ULTRA_@ENV@_RAW__DATA_HUB__ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP on TABLE ULTRA_@ENV@_RAW.DATA_HUB.ISSUE to role ULTRA_@ENV@_RAW__DATA_HUB__ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP on TABLE ULTRA_@ENV@_RAW.DATA_HUB.PUBLICATION to role ULTRA_@ENV@_RAW__DATA_HUB__ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP on TABLE ULTRA_@ENV@_RAW.DATA_HUB.PUBLISHER to role ULTRA_@ENV@_RAW__DATA_HUB__ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP on TABLE ULTRA_@ENV@_RAW.DATA_HUB.REF_FILE_FORMAT to role ULTRA_@ENV@_RAW__DATA_HUB__ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP on TABLE ULTRA_@ENV@_RAW.DATA_HUB.REF_INTERFACE to role ULTRA_@ENV@_RAW__DATA_HUB__ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP on TABLE ULTRA_@ENV@_RAW.DATA_HUB.REF_INTERVAL to role ULTRA_@ENV@_RAW__DATA_HUB__ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP on TABLE ULTRA_@ENV@_RAW.DATA_HUB.REF_METHOD to role ULTRA_@ENV@_RAW__DATA_HUB__ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP on TABLE ULTRA_@ENV@_RAW.DATA_HUB.REF_STATUS to role ULTRA_@ENV@_RAW__DATA_HUB__ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP on TABLE ULTRA_@ENV@_RAW.DATA_HUB.REF_STORAGE_METHOD to role ULTRA_@ENV@_RAW__DATA_HUB__ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP on TABLE ULTRA_@ENV@_RAW.DATA_HUB.REF_TRANSFER_METHOD to role ULTRA_@ENV@_RAW__DATA_HUB__ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP on TABLE ULTRA_@ENV@_RAW.DATA_HUB.REF_TRIGGER_TYPE to role ULTRA_@ENV@_RAW__DATA_HUB__ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP on TABLE ULTRA_@ENV@_RAW.DATA_HUB.SUBSCRIBER to role ULTRA_@ENV@_RAW__DATA_HUB__ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP on TABLE ULTRA_@ENV@_RAW.DATA_HUB.SUBSCRIPTION to role ULTRA_@ENV@_RAW__DATA_HUB__ADMIN COPY CURRENT GRANTS;



