create or replace TABLE MYDB_@ENV@_RAW.DATA_HUB.ISSUE_EIMARC_5490 (
	ISSUEID NUMBER(38,0) NOT NULL autoincrement start 30000 increment 1 order,
	PUBLICATIONCODE VARCHAR(25) NOT NULL,
	STATUSCODE VARCHAR(25) NOT NULL,
	REPORTDATE DATE NOT NULL,
	SRCDFPUBLISHERID VARCHAR(255),
	SRCDFPUBLICATIONID VARCHAR(255),
	SRCDFISSUEID VARCHAR(255),
	SRCISSUENAME VARCHAR(255),
	SRCDFCREATEDDATE DATE,
	DATALAKEPATH VARCHAR(255) NOT NULL DEFAULT '/Raw Data Zone/...',
	ISSUENAME VARCHAR(255) NOT NULL,
	PUBLICATIONSEQ NUMBER(38,0) NOT NULL DEFAULT -1,
	DAILYPUBLICATIONSEQ NUMBER(38,0) NOT NULL DEFAULT -1,
	FIRSTRECORDSEQ NUMBER(38,0),
	LASTRECORDSEQ NUMBER(38,0),
	FIRSTRECORDCHECKSUM VARCHAR(255),
	LASTRECORDCHECKSUM VARCHAR(255),
	PERIODSTARTTIME TIMESTAMP_TZ(9) NOT NULL,
	PERIODENDTIME TIMESTAMP_TZ(9),
	PERIODSTARTTIMEUTC TIMESTAMP_TZ(9),
	PERIODENDTIMEUTC TIMESTAMP_TZ(9),
	ISSUECONSUMEDDATE TIMESTAMP_TZ(9),
	RECORDCOUNT NUMBER(38,0) NOT NULL,
	RETRYCOUNT NUMBER(38,0) NOT NULL DEFAULT 0,
	ETLEXECUTIONID VARCHAR(255),
	CREATEDBY VARCHAR(255) NOT NULL,
	CREATEDDTM TIMESTAMP_TZ(9) NOT NULL,
	MODIFIEDBY VARCHAR(255),
	MODIFIEDDTM TIMESTAMP_TZ(9),
	constraint PK_ISSUEISSUEID primary key (ISSUEID),
	constraint FK_ISSUE__PUBLICATION__PUBLICATIONCODE foreign key (PUBLICATIONCODE) references MYDB_@ENV@_RAW.DATA_HUB.PUBLICATION(PUBLICATIONCODE),
	constraint FK_ISSUE__REFSTATUS__STATUSCODE foreign key (STATUSCODE) references MYDB_@ENV@_RAW.DATA_HUB.REF_STATUS(STATUSCODE)
);

GRANT OWNERSHIP on TABLE MYDB_@ENV@_RAW.DATA_HUB.ISSUE_EIMARC_5490 to role MYDB_@ENV@_RAW__DATA_HUB__ADMIN COPY CURRENT GRANTS;

INSERT INTO MYDB_@ENV@_RAW.DATA_HUB.ISSUE_EIMARC_5490(
	 ISSUEID
	,PUBLICATIONCODE
	,STATUSCODE
	,REPORTDATE
	,SRCDFPUBLISHERID
	,SRCDFPUBLICATIONID 
	,SRCDFISSUEID
	,SRCISSUENAME
	,SRCDFCREATEDDATE
	,DATALAKEPATH
	,ISSUENAME 
	,PUBLICATIONSEQ 
	,DAILYPUBLICATIONSEQ 
	,FIRSTRECORDSEQ
	,LASTRECORDSEQ 
	,FIRSTRECORDCHECKSUM
	,LASTRECORDCHECKSUM 
	,PERIODSTARTTIME
	,PERIODENDTIME 
	,PERIODSTARTTIMEUTC 
	,PERIODENDTIMEUTC 
	,ISSUECONSUMEDDATE 
	,RECORDCOUNT 
	,RETRYCOUNT 
	,ETLEXECUTIONID 
	,CREATEDBY 
	,CREATEDDTM 
	,MODIFIEDBY 
	,MODIFIEDDTM 
)
SELECT 
	 ISSUEID
	,PUBLICATIONCODE
	,STATUSCODE
	,REPORTDATE
	,SRCDFPUBLISHERID
	,SRCDFPUBLICATIONID 
	,SRCDFISSUEID
	,SRCISSUENAME
	,SRCDFCREATEDDATE
	,DATALAKEPATH
	,ISSUENAME 
	,PUBLICATIONSEQ 
	,DAILYPUBLICATIONSEQ 
	,FIRSTRECORDSEQ
	,LASTRECORDSEQ 
	,FIRSTRECORDCHECKSUM
	,LASTRECORDCHECKSUM 
	,PERIODSTARTTIME
	,PERIODENDTIME 
	,PERIODSTARTTIMEUTC 
	,PERIODENDTIMEUTC 
	,ISSUECONSUMEDDATE 
	,RECORDCOUNT 
	,RETRYCOUNT 
	,ETLEXECUTIONID 
	,CREATEDBY 
	,CREATEDDTM 
	,MODIFIEDBY 
	,MODIFIEDDTM 
from MYDB_@ENV@_RAW.DATA_HUB.ISSUE
order by CREATEDDTM asc;

alter table  MYDB_@ENV@_RAW.DATA_HUB.ISSUE             rename to  MYDB_@ENV@_RAW.DATA_HUB.ISSUE_BCK_EIMARC_5490_20250130;
alter table  MYDB_@ENV@_RAW.DATA_HUB.ISSUE_EIMARC_5490 rename to  MYDB_@ENV@_RAW.DATA_HUB.ISSUE;

GRANT OWNERSHIP on TABLE MYDB_@ENV@_RAW.DATA_HUB.ISSUE to role MYDB_@ENV@_RAW__DATA_HUB__ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP on TABLE MYDB_@ENV@_RAW.DATA_HUB.ISSUE_BCK_EIMARC_5490_20250130 to role MYDB_@ENV@_RAW__DATA_HUB__ADMIN COPY CURRENT GRANTS;