
function SelectCountryArea(){
	// ON selection of category this function will work
	
	removeAllOptions(document.CountryAreaList.DimCountryAreaID);
	//addOption(document.drop_list.State, "", "State", "");
	
	if(document.CountryAreaList.DimCountryID.value == '233'){ // US
		addOption(document.CountryAreaList.DimCountryAreaID,"1", "Alaska");
		addOption(document.CountryAreaList.DimCountryAreaID,"2", "Alabama");
		addOption(document.CountryAreaList.DimCountryAreaID,"3", "Arkansas");
		addOption(document.CountryAreaList.DimCountryAreaID,"4", "Arizona");
		addOption(document.CountryAreaList.DimCountryAreaID,"5", "California");
		addOption(document.CountryAreaList.DimCountryAreaID,"6", "Colorado");
		addOption(document.CountryAreaList.DimCountryAreaID,"7", "Connecticut");
		addOption(document.CountryAreaList.DimCountryAreaID,"8", "Delaware");
		addOption(document.CountryAreaList.DimCountryAreaID,"9", "Florida");
		addOption(document.CountryAreaList.DimCountryAreaID,"10", "Georgia");
		addOption(document.CountryAreaList.DimCountryAreaID,"11", "Hawaii");
		addOption(document.CountryAreaList.DimCountryAreaID,"12", "Iowa");
		addOption(document.CountryAreaList.DimCountryAreaID,"13", "Idaho");
		addOption(document.CountryAreaList.DimCountryAreaID,"14", "Illinois");
		addOption(document.CountryAreaList.DimCountryAreaID,"15", "Indiana");
		addOption(document.CountryAreaList.DimCountryAreaID,"16", "Kansas");
		addOption(document.CountryAreaList.DimCountryAreaID,"17", "Kentucky");
		addOption(document.CountryAreaList.DimCountryAreaID,"18", "Louisiana");
		addOption(document.CountryAreaList.DimCountryAreaID,"19", "Massachusetts");
		addOption(document.CountryAreaList.DimCountryAreaID,"20", "Maryland");
		addOption(document.CountryAreaList.DimCountryAreaID,"21", "Maine");
		addOption(document.CountryAreaList.DimCountryAreaID,"22", "Michigan");
		addOption(document.CountryAreaList.DimCountryAreaID,"23", "Minnesota");
		addOption(document.CountryAreaList.DimCountryAreaID,"24", "Missouri");
		addOption(document.CountryAreaList.DimCountryAreaID,"25", "Mississippi");
		addOption(document.CountryAreaList.DimCountryAreaID,"26", "Montana");
		addOption(document.CountryAreaList.DimCountryAreaID,"27", "Nebraska");
		addOption(document.CountryAreaList.DimCountryAreaID,"28", "North Carolina");
		addOption(document.CountryAreaList.DimCountryAreaID,"29", "North Dakota");
		addOption(document.CountryAreaList.DimCountryAreaID,"30", "New Hampshire");
		addOption(document.CountryAreaList.DimCountryAreaID,"31", "New Jersey");
		addOption(document.CountryAreaList.DimCountryAreaID,"32", "New Mexico");
		addOption(document.CountryAreaList.DimCountryAreaID,"33", "New York");
		addOption(document.CountryAreaList.DimCountryAreaID,"34", "Nevada");
		addOption(document.CountryAreaList.DimCountryAreaID,"35", "Ohio");
		addOption(document.CountryAreaList.DimCountryAreaID,"36", "Oklahoma");
		addOption(document.CountryAreaList.DimCountryAreaID,"37", "Oregon");
		addOption(document.CountryAreaList.DimCountryAreaID,"38", "Pennsylvania");
		addOption(document.CountryAreaList.DimCountryAreaID,"39", "Rhode Island");
		addOption(document.CountryAreaList.DimCountryAreaID,"40", "South Carolina");
		addOption(document.CountryAreaList.DimCountryAreaID,"41", "South Dakota");
		addOption(document.CountryAreaList.DimCountryAreaID,"42", "Tennessee");
		addOption(document.CountryAreaList.DimCountryAreaID,"43", "Texas");
		addOption(document.CountryAreaList.DimCountryAreaID,"44", "Utah");
		addOption(document.CountryAreaList.DimCountryAreaID,"45", "Virginia");
		addOption(document.CountryAreaList.DimCountryAreaID,"46", "Vermont");
		addOption(document.CountryAreaList.DimCountryAreaID,"47", "Washington");
		addOption(document.CountryAreaList.DimCountryAreaID,"48", "Wisconsin");
		addOption(document.CountryAreaList.DimCountryAreaID,"49", "West Virginia");
		addOption(document.CountryAreaList.DimCountryAreaID,"50", "Wyoming");
	} else if(document.CountryAreaList.DimCountryID.value == '38'){ // Canada
		addOption(document.CountryAreaList.DimCountryAreaID,"61", "Alberta");
		addOption(document.CountryAreaList.DimCountryAreaID,"58", "British Columbia");
		addOption(document.CountryAreaList.DimCountryAreaID,"57", "Manitoba");
		addOption(document.CountryAreaList.DimCountryAreaID,"56", "New Brunswick");
		addOption(document.CountryAreaList.DimCountryAreaID,"62", "Newfoundland and Labrador");
		addOption(document.CountryAreaList.DimCountryAreaID,"63", "Northwest Territories");
		addOption(document.CountryAreaList.DimCountryAreaID,"55", "Nova Scotia");
		addOption(document.CountryAreaList.DimCountryAreaID,"65", "Nunavut");
		addOption(document.CountryAreaList.DimCountryAreaID,"53", "Ontario");
		addOption(document.CountryAreaList.DimCountryAreaID,"59", "Prince Edward Island");
		addOption(document.CountryAreaList.DimCountryAreaID,"54", "Quebec");
		addOption(document.CountryAreaList.DimCountryAreaID,"60", "Saskatchewan");
		addOption(document.CountryAreaList.DimCountryAreaID,"64", "Yukon");
	} else if(document.CountryAreaList.DimCountryID.value == '13'){ // Australia
		addOption(document.CountryAreaList.DimCountryAreaID,"66", "Australian Capital Territory");
		addOption(document.CountryAreaList.DimCountryAreaID,"67", "Jervis Bay Territory");
		addOption(document.CountryAreaList.DimCountryAreaID,"68", "New South Wales");
		addOption(document.CountryAreaList.DimCountryAreaID,"69", "Northern Territory");
		addOption(document.CountryAreaList.DimCountryAreaID,"70", "Queensland");
		addOption(document.CountryAreaList.DimCountryAreaID,"71", "South Australia");
		addOption(document.CountryAreaList.DimCountryAreaID,"72", "Tasmania");
		addOption(document.CountryAreaList.DimCountryAreaID,"73", "Victoria");
		addOption(document.CountryAreaList.DimCountryAreaID,"74", "Western Australia");
	} else if(document.CountryAreaList.DimCountryID.value == '77'){ // UK
		addOption(document.CountryAreaList.DimCountryAreaID,"75", "East Midlands");
		addOption(document.CountryAreaList.DimCountryAreaID,"76", "East of England");
		addOption(document.CountryAreaList.DimCountryAreaID,"77", "Greater London");
		addOption(document.CountryAreaList.DimCountryAreaID,"78", "North East England");
		addOption(document.CountryAreaList.DimCountryAreaID,"79", "North West England");
		addOption(document.CountryAreaList.DimCountryAreaID,"84", "Northern Ireland");
		addOption(document.CountryAreaList.DimCountryAreaID,"85", "Scotland");
		addOption(document.CountryAreaList.DimCountryAreaID,"80", "South East England");
		addOption(document.CountryAreaList.DimCountryAreaID,"81", "South West England");
		addOption(document.CountryAreaList.DimCountryAreaID,"86", "Wales");
		addOption(document.CountryAreaList.DimCountryAreaID,"82", "West Midlands");
		addOption(document.CountryAreaList.DimCountryAreaID,"83", "Yorkshire and the Humber");
	} else if(document.CountryAreaList.DimCountryID.value == '57'){ // Germany
		addOption(document.CountryAreaList.DimCountryAreaID,"292", "Baden-Württemberg");
		addOption(document.CountryAreaList.DimCountryAreaID,"293", "Bavaria (Bayem)");
		addOption(document.CountryAreaList.DimCountryAreaID,"294", "Berlin");
		addOption(document.CountryAreaList.DimCountryAreaID,"295", "Brandenburg");
		addOption(document.CountryAreaList.DimCountryAreaID,"296", "Bremen");
		addOption(document.CountryAreaList.DimCountryAreaID,"297", "Hamburg");
		addOption(document.CountryAreaList.DimCountryAreaID,"298", "Hesse (Hessen)");
		addOption(document.CountryAreaList.DimCountryAreaID,"299", "Lower Saxon (Niedersachsen)");
		addOption(document.CountryAreaList.DimCountryAreaID,"300", "Mecklenburg-Vorpommern");
		addOption(document.CountryAreaList.DimCountryAreaID,"301", "North Rhine-Westphalia (Nordrhein-Westfalen)");
		addOption(document.CountryAreaList.DimCountryAreaID,"302", "Rhineland-Palatinate (Rheinland-Pfalz)");
		addOption(document.CountryAreaList.DimCountryAreaID,"303", "Saarland");
		addOption(document.CountryAreaList.DimCountryAreaID,"304", "Saxony (Sachsen)");
		addOption(document.CountryAreaList.DimCountryAreaID,"305", "Saxony-Anhalt (Sachsen-Anhalt)");
		addOption(document.CountryAreaList.DimCountryAreaID,"306", "Schleswig-Holstein");
		addOption(document.CountryAreaList.DimCountryAreaID,"307", "Thuringia (Thüringen)");
	} else if(document.CountryAreaList.DimCountryID.value == '68'){ // Spain
		addOption(document.CountryAreaList.DimCountryAreaID,"119", "A Coruña");
		addOption(document.CountryAreaList.DimCountryAreaID,"120", "Álava");
		addOption(document.CountryAreaList.DimCountryAreaID,"121", "Albacete");
		addOption(document.CountryAreaList.DimCountryAreaID,"122", "Alicante");
		addOption(document.CountryAreaList.DimCountryAreaID,"123", "Almería");
		addOption(document.CountryAreaList.DimCountryAreaID,"124", "Asturias");
		addOption(document.CountryAreaList.DimCountryAreaID,"125", "Ávila");
		addOption(document.CountryAreaList.DimCountryAreaID,"126", "Badajoz");
		addOption(document.CountryAreaList.DimCountryAreaID,"127", "Baleares");
		addOption(document.CountryAreaList.DimCountryAreaID,"128", "Barcelona");
		addOption(document.CountryAreaList.DimCountryAreaID,"129", "Burgos");
		addOption(document.CountryAreaList.DimCountryAreaID,"130", "Cáceres");
		addOption(document.CountryAreaList.DimCountryAreaID,"131", "Cádiz");
		addOption(document.CountryAreaList.DimCountryAreaID,"132", "Cantabria");
		addOption(document.CountryAreaList.DimCountryAreaID,"133", "Castellón");
		addOption(document.CountryAreaList.DimCountryAreaID,"134", "Ceuta");
		addOption(document.CountryAreaList.DimCountryAreaID,"135", "Ciudad Real");
		addOption(document.CountryAreaList.DimCountryAreaID,"136", "Córdoba");
		addOption(document.CountryAreaList.DimCountryAreaID,"137", "Cuenca");
		addOption(document.CountryAreaList.DimCountryAreaID,"138", "Girona");
		addOption(document.CountryAreaList.DimCountryAreaID,"139", "Granada");
		addOption(document.CountryAreaList.DimCountryAreaID,"140", "Guadalajara");
		addOption(document.CountryAreaList.DimCountryAreaID,"141", "Guipúzcoa");
		addOption(document.CountryAreaList.DimCountryAreaID,"142", "Huelva");
		addOption(document.CountryAreaList.DimCountryAreaID,"143", "Huesca");
		addOption(document.CountryAreaList.DimCountryAreaID,"144", "Jaén");
		addOption(document.CountryAreaList.DimCountryAreaID,"145", "La Rioja");
		addOption(document.CountryAreaList.DimCountryAreaID,"146", "Las Palmas");
		addOption(document.CountryAreaList.DimCountryAreaID,"147", "León");
		addOption(document.CountryAreaList.DimCountryAreaID,"148", "Lleida");
		addOption(document.CountryAreaList.DimCountryAreaID,"149", "Lugo");
		addOption(document.CountryAreaList.DimCountryAreaID,"150", "Madrid");
		addOption(document.CountryAreaList.DimCountryAreaID,"151", "Málaga");
		addOption(document.CountryAreaList.DimCountryAreaID,"152", "Melilla");
		addOption(document.CountryAreaList.DimCountryAreaID,"153", "Murcia");
		addOption(document.CountryAreaList.DimCountryAreaID,"154", "Navarra");
		addOption(document.CountryAreaList.DimCountryAreaID,"155", "Ourense");
		addOption(document.CountryAreaList.DimCountryAreaID,"156", "Palencia");
		addOption(document.CountryAreaList.DimCountryAreaID,"157", "Pontevedra");
		addOption(document.CountryAreaList.DimCountryAreaID,"158", "Salamanca");
		addOption(document.CountryAreaList.DimCountryAreaID,"159", "Santa Cruz de Tenerife");
		addOption(document.CountryAreaList.DimCountryAreaID,"160", "Segovia");
		addOption(document.CountryAreaList.DimCountryAreaID,"161", "Sevilla");
		addOption(document.CountryAreaList.DimCountryAreaID,"162", "Soria");
		addOption(document.CountryAreaList.DimCountryAreaID,"163", "Tarragona");
		addOption(document.CountryAreaList.DimCountryAreaID,"164", "Teruel");
		addOption(document.CountryAreaList.DimCountryAreaID,"165", "Toledo");
		addOption(document.CountryAreaList.DimCountryAreaID,"166", "Valencia");
		addOption(document.CountryAreaList.DimCountryAreaID,"167", "Valladolid");
		addOption(document.CountryAreaList.DimCountryAreaID,"168", "Vizcaya");
		addOption(document.CountryAreaList.DimCountryAreaID,"169", "Zamora");
		addOption(document.CountryAreaList.DimCountryAreaID,"170", "Zaragoza");
	} else if(document.CountryAreaList.DimCountryID.value == '75'){ // France
		addOption(document.CountryAreaList.DimCountryAreaID,"310", "Auvergne-Rhône-Alpes");
		addOption(document.CountryAreaList.DimCountryAreaID,"311", "Bourgogne-Franche-Comté");
		addOption(document.CountryAreaList.DimCountryAreaID,"312", "Brittany");
		addOption(document.CountryAreaList.DimCountryAreaID,"313", "Centre-Val de Loire");
		addOption(document.CountryAreaList.DimCountryAreaID,"320", "Corsica");
		addOption(document.CountryAreaList.DimCountryAreaID,"308", "Grand Est");
		addOption(document.CountryAreaList.DimCountryAreaID,"316", "Hauts-de-France");
		addOption(document.CountryAreaList.DimCountryAreaID,"314", "Île-de-France");
		addOption(document.CountryAreaList.DimCountryAreaID,"317", "Normandy");
		addOption(document.CountryAreaList.DimCountryAreaID,"309", "Nouvelle-Aquitaine");
		addOption(document.CountryAreaList.DimCountryAreaID,"315", "Occitanie");
		addOption(document.CountryAreaList.DimCountryAreaID,"318", "Pays de la Loire");
		addOption(document.CountryAreaList.DimCountryAreaID,"319", "Provence-Alpes-Côte d'Azur (PACA)");	  
	} else if(document.CountryAreaList.DimCountryID.value == '105'){ // India
		addOption(document.CountryAreaList.DimCountryAreaID,"171", "Andaman and Nicobar Islands");
		addOption(document.CountryAreaList.DimCountryAreaID,"172", "Andhra Pradesh");
		addOption(document.CountryAreaList.DimCountryAreaID,"173", "Arunachal Pradesh");
		addOption(document.CountryAreaList.DimCountryAreaID,"174", "Assam");
		addOption(document.CountryAreaList.DimCountryAreaID,"175", "Bihar");
		addOption(document.CountryAreaList.DimCountryAreaID,"176", "Chandigarh");
		addOption(document.CountryAreaList.DimCountryAreaID,"177", "Chhattisgarh");
		addOption(document.CountryAreaList.DimCountryAreaID,"178", "Dadra and Nagar Haveli");
		addOption(document.CountryAreaList.DimCountryAreaID,"179", "Daman and Diu");
		addOption(document.CountryAreaList.DimCountryAreaID,"181", "Goa");
		addOption(document.CountryAreaList.DimCountryAreaID,"182", "Gujarat");
		addOption(document.CountryAreaList.DimCountryAreaID,"183", "Haryana");
		addOption(document.CountryAreaList.DimCountryAreaID,"184", "Himachal Pradesh");
		addOption(document.CountryAreaList.DimCountryAreaID,"185", "Jammu and Kashmir");
		addOption(document.CountryAreaList.DimCountryAreaID,"186", "Jharkhand");
		addOption(document.CountryAreaList.DimCountryAreaID,"187", "Karnataka");
		addOption(document.CountryAreaList.DimCountryAreaID,"188", "Kerala");
		addOption(document.CountryAreaList.DimCountryAreaID,"189", "Lakshadweep");
		addOption(document.CountryAreaList.DimCountryAreaID,"190", "Madhya Pradesh");
		addOption(document.CountryAreaList.DimCountryAreaID,"191", "Maharashtra");
		addOption(document.CountryAreaList.DimCountryAreaID,"192", "Manipur");
		addOption(document.CountryAreaList.DimCountryAreaID,"193", "Meghalaya");
		addOption(document.CountryAreaList.DimCountryAreaID,"194", "Mizoram");
		addOption(document.CountryAreaList.DimCountryAreaID,"195", "Nagaland");
		addOption(document.CountryAreaList.DimCountryAreaID,"180", "National Capital Territory of Delhi");
		addOption(document.CountryAreaList.DimCountryAreaID,"196", "Odisha");
		addOption(document.CountryAreaList.DimCountryAreaID,"197", "Puducherry");
		addOption(document.CountryAreaList.DimCountryAreaID,"198", "Punjab");
		addOption(document.CountryAreaList.DimCountryAreaID,"199", "Rajasthan");
		addOption(document.CountryAreaList.DimCountryAreaID,"200", "Sikkim");
		addOption(document.CountryAreaList.DimCountryAreaID,"201", "Tamil Nadu");
		addOption(document.CountryAreaList.DimCountryAreaID,"202", "Telangana");
		addOption(document.CountryAreaList.DimCountryAreaID,"203", "Tripura");
		addOption(document.CountryAreaList.DimCountryAreaID,"204", "Uttar Pradesh");
		addOption(document.CountryAreaList.DimCountryAreaID,"205", "Uttarakhand");
		addOption(document.CountryAreaList.DimCountryAreaID,"206", "West Bengal");
	} else if(document.CountryAreaList.DimCountryID.value == '157'){ // Mexico
		addOption(document.CountryAreaList.DimCountryAreaID,"87", "Aguascalientes");
		addOption(document.CountryAreaList.DimCountryAreaID,"88", "Baja California");
		addOption(document.CountryAreaList.DimCountryAreaID,"89", "Baja California Sur");
		addOption(document.CountryAreaList.DimCountryAreaID,"90", "Campeche");
		addOption(document.CountryAreaList.DimCountryAreaID,"91", "Chiapas");
		addOption(document.CountryAreaList.DimCountryAreaID,"92", "Chihuahua");
		addOption(document.CountryAreaList.DimCountryAreaID,"93", "Coahuila");
		addOption(document.CountryAreaList.DimCountryAreaID,"94", "Colima");
		addOption(document.CountryAreaList.DimCountryAreaID,"96", "Durango");
		addOption(document.CountryAreaList.DimCountryAreaID,"95", "Federal District");
		addOption(document.CountryAreaList.DimCountryAreaID,"97", "Guanajuato");
		addOption(document.CountryAreaList.DimCountryAreaID,"98", "Guerrero");
		addOption(document.CountryAreaList.DimCountryAreaID,"99", "Hidalgo");
		addOption(document.CountryAreaList.DimCountryAreaID,"100", "Jalisco");
		addOption(document.CountryAreaList.DimCountryAreaID,"101", "Mexico State");
		addOption(document.CountryAreaList.DimCountryAreaID,"102", "Michoacán");
		addOption(document.CountryAreaList.DimCountryAreaID,"103", "Morelos");
		addOption(document.CountryAreaList.DimCountryAreaID,"104", "Nayarit");
		addOption(document.CountryAreaList.DimCountryAreaID,"105", "Nuevo León");
		addOption(document.CountryAreaList.DimCountryAreaID,"106", "Oaxaca");
		addOption(document.CountryAreaList.DimCountryAreaID,"107", "Puebla");
		addOption(document.CountryAreaList.DimCountryAreaID,"108", "Querétaro");
		addOption(document.CountryAreaList.DimCountryAreaID,"109", "Quintana Roo");
		addOption(document.CountryAreaList.DimCountryAreaID,"110", "San Luis Potosí");
		addOption(document.CountryAreaList.DimCountryAreaID,"111", "Sinaloa");
		addOption(document.CountryAreaList.DimCountryAreaID,"112", "Sonora");
		addOption(document.CountryAreaList.DimCountryAreaID,"113", "Tabasco");
		addOption(document.CountryAreaList.DimCountryAreaID,"114", "Tamaulipas");
		addOption(document.CountryAreaList.DimCountryAreaID,"115", "Tlaxcala");
		addOption(document.CountryAreaList.DimCountryAreaID,"116", "Veracruz");
		addOption(document.CountryAreaList.DimCountryAreaID,"117", "Yucatán");
		addOption(document.CountryAreaList.DimCountryAreaID,"118", "Zacatecas");	  
	} else if(document.CountryAreaList.DimCountryID.value == '177'){ // Philippines
		addOption(document.CountryAreaList.DimCountryAreaID,"210", "Abra");
		addOption(document.CountryAreaList.DimCountryAreaID,"211", "Agusan del Norte");
		addOption(document.CountryAreaList.DimCountryAreaID,"212", "Agusan del Sur");
		addOption(document.CountryAreaList.DimCountryAreaID,"213", "Aklan");
		addOption(document.CountryAreaList.DimCountryAreaID,"214", "Albay");
		addOption(document.CountryAreaList.DimCountryAreaID,"215", "Antique");
		addOption(document.CountryAreaList.DimCountryAreaID,"216", "Apayao");
		addOption(document.CountryAreaList.DimCountryAreaID,"217", "Aurora");
		addOption(document.CountryAreaList.DimCountryAreaID,"218", "Basilan");
		addOption(document.CountryAreaList.DimCountryAreaID,"219", "Bataan");
		addOption(document.CountryAreaList.DimCountryAreaID,"220", "Batanes");
		addOption(document.CountryAreaList.DimCountryAreaID,"221", "Batangas");
		addOption(document.CountryAreaList.DimCountryAreaID,"222", "Benguet");
		addOption(document.CountryAreaList.DimCountryAreaID,"223", "Biliran");
		addOption(document.CountryAreaList.DimCountryAreaID,"224", "Bohol");
		addOption(document.CountryAreaList.DimCountryAreaID,"225", "Bukidnon");
		addOption(document.CountryAreaList.DimCountryAreaID,"226", "Bulacan");
		addOption(document.CountryAreaList.DimCountryAreaID,"227", "Cagayan");
		addOption(document.CountryAreaList.DimCountryAreaID,"228", "Camarines Norte");
		addOption(document.CountryAreaList.DimCountryAreaID,"229", "Camarines Sur");
		addOption(document.CountryAreaList.DimCountryAreaID,"230", "Camiguin");
		addOption(document.CountryAreaList.DimCountryAreaID,"231", "Capiz");
		addOption(document.CountryAreaList.DimCountryAreaID,"232", "Catanduanes");
		addOption(document.CountryAreaList.DimCountryAreaID,"233", "Cavite");
		addOption(document.CountryAreaList.DimCountryAreaID,"234", "Cebu");
		addOption(document.CountryAreaList.DimCountryAreaID,"235", "Compostela Valley");
		addOption(document.CountryAreaList.DimCountryAreaID,"236", "Cotabato");
		addOption(document.CountryAreaList.DimCountryAreaID,"237", "Davao del Norte");
		addOption(document.CountryAreaList.DimCountryAreaID,"238", "Davao del Sur");
		addOption(document.CountryAreaList.DimCountryAreaID,"239", "Davao Occidental");
		addOption(document.CountryAreaList.DimCountryAreaID,"240", "Davao Oriental");
		addOption(document.CountryAreaList.DimCountryAreaID,"241", "Dinagat Islands");
		addOption(document.CountryAreaList.DimCountryAreaID,"242", "Eastern Samar");
		addOption(document.CountryAreaList.DimCountryAreaID,"243", "Guimaras");
		addOption(document.CountryAreaList.DimCountryAreaID,"244", "Ifugao");
		addOption(document.CountryAreaList.DimCountryAreaID,"245", "Ilocos Norte");
		addOption(document.CountryAreaList.DimCountryAreaID,"246", "Ilocos Sur");
		addOption(document.CountryAreaList.DimCountryAreaID,"247", "Iloilo");
		addOption(document.CountryAreaList.DimCountryAreaID,"248", "Isabela");
		addOption(document.CountryAreaList.DimCountryAreaID,"249", "Kalinga");
		addOption(document.CountryAreaList.DimCountryAreaID,"250", "La Union");
		addOption(document.CountryAreaList.DimCountryAreaID,"251", "Laguna");
		addOption(document.CountryAreaList.DimCountryAreaID,"252", "Lanao del Norte");
		addOption(document.CountryAreaList.DimCountryAreaID,"253", "Lanao del Sur");
		addOption(document.CountryAreaList.DimCountryAreaID,"254", "Leyte");
		addOption(document.CountryAreaList.DimCountryAreaID,"255", "Maguindanao");
		addOption(document.CountryAreaList.DimCountryAreaID,"256", "Marinduque");
		addOption(document.CountryAreaList.DimCountryAreaID,"257", "Masbate");
		addOption(document.CountryAreaList.DimCountryAreaID,"291", "Metro Manila");
		addOption(document.CountryAreaList.DimCountryAreaID,"258", "Misamis Occidental");
		addOption(document.CountryAreaList.DimCountryAreaID,"259", "Misamis Oriental");
		addOption(document.CountryAreaList.DimCountryAreaID,"260", "Mountain Province");
		addOption(document.CountryAreaList.DimCountryAreaID,"261", "Negros Occidental");
		addOption(document.CountryAreaList.DimCountryAreaID,"262", "Negros Oriental");
		addOption(document.CountryAreaList.DimCountryAreaID,"263", "Northern Samar");
		addOption(document.CountryAreaList.DimCountryAreaID,"264", "Nueva Ecija");
		addOption(document.CountryAreaList.DimCountryAreaID,"265", "Nueva Vizcaya");
		addOption(document.CountryAreaList.DimCountryAreaID,"266", "Occidental Mindoro");
		addOption(document.CountryAreaList.DimCountryAreaID,"267", "Oriental Mindoro");
		addOption(document.CountryAreaList.DimCountryAreaID,"268", "Palawan");
		addOption(document.CountryAreaList.DimCountryAreaID,"269", "Pampanga");
		addOption(document.CountryAreaList.DimCountryAreaID,"270", "Pangasinan");
		addOption(document.CountryAreaList.DimCountryAreaID,"271", "Quezon");
		addOption(document.CountryAreaList.DimCountryAreaID,"272", "Quirino");
		addOption(document.CountryAreaList.DimCountryAreaID,"273", "Rizal");
		addOption(document.CountryAreaList.DimCountryAreaID,"274", "Romblon");
		addOption(document.CountryAreaList.DimCountryAreaID,"275", "Samar");
		addOption(document.CountryAreaList.DimCountryAreaID,"276", "Sarangani");
		addOption(document.CountryAreaList.DimCountryAreaID,"277", "Siquijor");
		addOption(document.CountryAreaList.DimCountryAreaID,"278", "Sorsogon");
		addOption(document.CountryAreaList.DimCountryAreaID,"279", "South Cotabato");
		addOption(document.CountryAreaList.DimCountryAreaID,"280", "Southern Leyte");
		addOption(document.CountryAreaList.DimCountryAreaID,"281", "Sultan Kudarat");
		addOption(document.CountryAreaList.DimCountryAreaID,"282", "Sulu");
		addOption(document.CountryAreaList.DimCountryAreaID,"283", "Surigao del Norte");
		addOption(document.CountryAreaList.DimCountryAreaID,"284", "Surigao del Sur");
		addOption(document.CountryAreaList.DimCountryAreaID,"285", "Tarlac");
		addOption(document.CountryAreaList.DimCountryAreaID,"286", "Tawi-Tawi");
		addOption(document.CountryAreaList.DimCountryAreaID,"287", "Zambales");
		addOption(document.CountryAreaList.DimCountryAreaID,"288", "Zamboanga del Norte");
		addOption(document.CountryAreaList.DimCountryAreaID,"289", "Zamboanga del Sur");
		addOption(document.CountryAreaList.DimCountryAreaID,"290", "Zamboanga Sibugay");
	} else if(document.CountryAreaList.DimCountryID.value == '178'){ // Pakistan
		addOption(document.CountryAreaList.DimCountryAreaID,"209", "Balochistan");
		addOption(document.CountryAreaList.DimCountryAreaID,"207", "Punjab");
		addOption(document.CountryAreaList.DimCountryAreaID,"208", "Sindh"); 
	} else {
		addOption(document.CountryAreaList.DimCountryAreaID,"-1", "-- Select --");
	}
}
////////////////// 

function removeAllOptions(selectbox)
{
	var i;
	for(i=selectbox.options.length-1;i>=0;i--)
	{
		//selectbox.options.remove(i);
		selectbox.remove(i);
	}
}


function addOption(selectbox, value, text )
{
	var optn = document.createElement("OPTION");
	optn.text = text;
	optn.value = value;

	selectbox.options.add(optn);
}
