version: 0.2
phases:
  # install:
  #   runtime-versions:
  #     python: 3.8
  #   commands:
  #     - pip install -r hubspot_sync/requirements.txt
  #     - pip install -r hubspot_sync/tests/requirements.txt
  build:
    commands:
      # trigger the unit tests here
      - echo 'Running unit tests'
      # - python -m pytest
