---- ENV: DEV
---- DATABASE: MYDB_DEV_RAW
USE ROLE ADMINISTRATOR;
CREATE SCHEMA IF NOT EXISTS MYDB_DEV_RAW.DATA_HUB;

USE ROLE SECURITYADMIN;
-- Create Schema Read Role
CREATE ROLE MYDB_DEV_RAW_DATA_HUB_R;
GRANT USAGE ON DATABASE MYDB_DEV_RAW TO ROLE MYDB_DEV_RAW_DATA_HUB_R;
GRANT USAGE ON SCHEMA MYDB_DEV_RAW.DATA_HUB TO ROLE MYDB_DEV_RAW_DATA_HUB_R;
GRANT USAGE ON SCHEMA MYDB_DEV_RAW.DATA_HUB TO ROLE PIPELINE_DEV_SVC_ACCESS;
GRANT SELECT ON FUTURE TABLES IN SCHEMA MYDB_DEV_RAW.DATA_HUB TO ROLE MYDB_DEV_RAW_DATA_HUB_R;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA MYDB_DEV_RAW.DATA_HUB TO ROLE MYDB_DEV_RAW_DATA_HUB_R;

-- Create Schema Write Role
CREATE ROLE MYDB_DEV_RAW_DATA_HUB_W;
GRANT ROLE MYDB_DEV_RAW_DATA_HUB_R TO ROLE MYDB_DEV_RAW_DATA_HUB_W;
GRANT DELETE, INSERT, UPDATE, TRUNCATE ON FUTURE TABLES IN SCHEMA MYDB_DEV_RAW.DATA_HUB TO ROLE MYDB_DEV_RAW_DATA_HUB_W;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA MYDB_DEV_RAW.DATA_HUB TO ROLE MYDB_DEV_RAW_DATA_HUB_W;        
--GRANT USAGE ON FUTURE INTEGRATIONS IN SCHEMA MYDB_DEV_RAW.DATA_HUB TO ROLE MYDB_DEV_RAW_DATA_HUB_W;      
GRANT MONITOR, OPERATE ON FUTURE PIPES IN SCHEMA MYDB_DEV_RAW.DATA_HUB TO ROLE MYDB_DEV_RAW_DATA_HUB_W;    
GRANT USAGE ON FUTURE STAGES IN SCHEMA MYDB_DEV_RAW.DATA_HUB TO ROLE MYDB_DEV_RAW_DATA_HUB_W;
GRANT SELECT ON FUTURE STREAMS IN SCHEMA MYDB_DEV_RAW.DATA_HUB TO ROLE MYDB_DEV_RAW_DATA_HUB_W;

-- Create Schema Admin Role
CREATE ROLE                              MYDB_DEV_RAW_DATA_HUB_ADMIN;
GRANT ROLE                               MYDB_DEV_RAW_DATA_HUB_W     TO ROLE MYDB_DEV_RAW_DATA_HUB_ADMIN;  
GRANT ROLE                               MYDB_DEV_RAW_DATA_HUB_ADMIN TO ROLE SYSADMIN;
GRANT ROLE                               MYDB_DEV_RAW_DATA_HUB_ADMIN TO ROLE PIPELINE_DEV_SVC_ACCESS;       
GRANT CREATE FILE FORMAT ON SCHEMA       MYDB_DEV_RAW.DATA_HUB       TO ROLE MYDB_DEV_RAW_DATA_HUB_ADMIN;  
GRANT CREATE MATERIALIZED VIEW ON SCHEMA MYDB_DEV_RAW.DATA_HUB       TO ROLE MYDB_DEV_RAW_DATA_HUB_ADMIN;  
GRANT CREATE PIPE ON SCHEMA              MYDB_DEV_RAW.DATA_HUB       TO ROLE MYDB_DEV_RAW_DATA_HUB_ADMIN;  
GRANT CREATE PROCEDURE ON SCHEMA         MYDB_DEV_RAW.DATA_HUB       TO ROLE MYDB_DEV_RAW_DATA_HUB_ADMIN;  
GRANT CREATE SEQUENCE ON SCHEMA          MYDB_DEV_RAW.DATA_HUB       TO ROLE MYDB_DEV_RAW_DATA_HUB_ADMIN;  
GRANT CREATE STAGE ON SCHEMA             MYDB_DEV_RAW.DATA_HUB       TO ROLE MYDB_DEV_RAW_DATA_HUB_ADMIN;  
GRANT CREATE STREAM ON SCHEMA            MYDB_DEV_RAW.DATA_HUB       TO ROLE MYDB_DEV_RAW_DATA_HUB_ADMIN;  
GRANT CREATE TABLE ON SCHEMA             MYDB_DEV_RAW.DATA_HUB       TO ROLE MYDB_DEV_RAW_DATA_HUB_ADMIN;  
GRANT CREATE TAG ON SCHEMA               MYDB_DEV_RAW.DATA_HUB       TO ROLE MYDB_DEV_RAW_DATA_HUB_ADMIN;  
GRANT CREATE TASK ON SCHEMA              MYDB_DEV_RAW.DATA_HUB       TO ROLE MYDB_DEV_RAW_DATA_HUB_ADMIN;  
GRANT CREATE TEMPORARY TABLE ON SCHEMA   MYDB_DEV_RAW.DATA_HUB       TO ROLE MYDB_DEV_RAW_DATA_HUB_ADMIN;  
GRANT CREATE VIEW ON SCHEMA              MYDB_DEV_RAW.DATA_HUB       TO ROLE MYDB_DEV_RAW_DATA_HUB_ADMIN;  



-- Glue Access to env
GRANT ROLE  MYDB_DEV_RAW_DATA_HUB_ADMIN        TO ROLE mydb_DEV_dw31_raw_admin;


-- DE Access to DEV env.
GRANT ROLE  MYDB_DEV_RAW_DATA_HUB_ADMIN       TO ROLE DE_ELEVATED;
GRANT ROLE  MYDB_DEV_RAW_DATA_HUB_ADMIN       TO ROLE DE_COMMON;



-- DE Access to DEV env.
GRANT ROLE  MYDB_DEV_RAW_DATA_HUB_ADMIN       TO ROLE DE_ELEVATED;
GRANT ROLE  MYDB_DEV_RAW_DATA_HUB_ADMIN       TO ROLE DE_COMMON;


-- Cross DB Permissions
GRANT ROLE  MYDB_DEV_RAW_DATA_HUB_R                TO ROLE mydb_DEV_dw31_curation_admin;
GRANT ROLE  MYDB_DEV_CURATION_DATA_HUB_R           TO ROLE mydb_DEV_dw31_warehouse_admin;

---- ENV: STAGE
---- DATABASE: MYDB_STAGE_RAW
USE ROLE ADMINISTRATOR;
CREATE SCHEMA IF NOT EXISTS MYDB_STAGE_RAW.DATA_HUB;

USE ROLE SECURITYADMIN;
-- Create Schema Read Role
CREATE ROLE MYDB_STAGE_RAW_DATA_HUB_R;
GRANT USAGE ON DATABASE MYDB_STAGE_RAW TO ROLE MYDB_STAGE_RAW_DATA_HUB_R;
GRANT USAGE ON SCHEMA MYDB_STAGE_RAW.DATA_HUB TO ROLE MYDB_STAGE_RAW_DATA_HUB_R;
GRANT USAGE ON SCHEMA MYDB_STAGE_RAW.DATA_HUB TO ROLE PIPELINE_STAGE_SVC_ACCESS;
GRANT SELECT ON FUTURE TABLES IN SCHEMA MYDB_STAGE_RAW.DATA_HUB TO ROLE MYDB_STAGE_RAW_DATA_HUB_R;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA MYDB_STAGE_RAW.DATA_HUB TO ROLE MYDB_STAGE_RAW_DATA_HUB_R;

-- Create Schema Write Role
CREATE ROLE MYDB_STAGE_RAW_DATA_HUB_W;
GRANT ROLE MYDB_STAGE_RAW_DATA_HUB_R TO ROLE MYDB_STAGE_RAW_DATA_HUB_W;
GRANT DELETE, INSERT, UPDATE, TRUNCATE ON FUTURE TABLES IN SCHEMA MYDB_STAGE_RAW.DATA_HUB TO ROLE MYDB_STAGE_RAW_DATA_HUB_W;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA MYDB_STAGE_RAW.DATA_HUB TO ROLE MYDB_STAGE_RAW_DATA_HUB_W;    
--GRANT USAGE ON FUTURE INTEGRATIONS IN SCHEMA MYDB_STAGE_RAW.DATA_HUB TO ROLE MYDB_STAGE_RAW_DATA_HUB_W;  
GRANT MONITOR, OPERATE ON FUTURE PIPES IN SCHEMA MYDB_STAGE_RAW.DATA_HUB TO ROLE MYDB_STAGE_RAW_DATA_HUB_W;
GRANT USAGE ON FUTURE STAGES IN SCHEMA MYDB_STAGE_RAW.DATA_HUB TO ROLE MYDB_STAGE_RAW_DATA_HUB_W;
GRANT SELECT ON FUTURE STREAMS IN SCHEMA MYDB_STAGE_RAW.DATA_HUB TO ROLE MYDB_STAGE_RAW_DATA_HUB_W;        

-- Create Schema Admin Role
CREATE ROLE                              MYDB_STAGE_RAW_DATA_HUB_ADMIN;
GRANT ROLE                               MYDB_STAGE_RAW_DATA_HUB_W     TO ROLE MYDB_STAGE_RAW_DATA_HUB_ADMIN;
GRANT ROLE                               MYDB_STAGE_RAW_DATA_HUB_ADMIN TO ROLE SYSADMIN;
GRANT ROLE                               MYDB_STAGE_RAW_DATA_HUB_ADMIN TO ROLE PIPELINE_STAGE_SVC_ACCESS;   
GRANT CREATE FILE FORMAT ON SCHEMA       MYDB_STAGE_RAW.DATA_HUB       TO ROLE MYDB_STAGE_RAW_DATA_HUB_ADMIN;
GRANT CREATE MATERIALIZED VIEW ON SCHEMA MYDB_STAGE_RAW.DATA_HUB       TO ROLE MYDB_STAGE_RAW_DATA_HUB_ADMIN;
GRANT CREATE PIPE ON SCHEMA              MYDB_STAGE_RAW.DATA_HUB       TO ROLE MYDB_STAGE_RAW_DATA_HUB_ADMIN;
GRANT CREATE PROCEDURE ON SCHEMA         MYDB_STAGE_RAW.DATA_HUB       TO ROLE MYDB_STAGE_RAW_DATA_HUB_ADMIN;
GRANT CREATE SEQUENCE ON SCHEMA          MYDB_STAGE_RAW.DATA_HUB       TO ROLE MYDB_STAGE_RAW_DATA_HUB_ADMIN;
GRANT CREATE STAGE ON SCHEMA             MYDB_STAGE_RAW.DATA_HUB       TO ROLE MYDB_STAGE_RAW_DATA_HUB_ADMIN;
GRANT CREATE STREAM ON SCHEMA            MYDB_STAGE_RAW.DATA_HUB       TO ROLE MYDB_STAGE_RAW_DATA_HUB_ADMIN;
GRANT CREATE TABLE ON SCHEMA             MYDB_STAGE_RAW.DATA_HUB       TO ROLE MYDB_STAGE_RAW_DATA_HUB_ADMIN;
GRANT CREATE TAG ON SCHEMA               MYDB_STAGE_RAW.DATA_HUB       TO ROLE MYDB_STAGE_RAW_DATA_HUB_ADMIN;
GRANT CREATE TASK ON SCHEMA              MYDB_STAGE_RAW.DATA_HUB       TO ROLE MYDB_STAGE_RAW_DATA_HUB_ADMIN;
GRANT CREATE TEMPORARY TABLE ON SCHEMA   MYDB_STAGE_RAW.DATA_HUB       TO ROLE MYDB_STAGE_RAW_DATA_HUB_ADMIN;
GRANT CREATE VIEW ON SCHEMA              MYDB_STAGE_RAW.DATA_HUB       TO ROLE MYDB_STAGE_RAW_DATA_HUB_ADMIN;



-- Glue Access to env
GRANT ROLE  MYDB_STAGE_RAW_DATA_HUB_ADMIN        TO ROLE mydb_STAGE_dw31_raw_admin;
GRANT ROLE  MYDB_STAGE_CURATION_DATA_HUB_ADMIN   TO ROLE mydb_STAGE_dw31_curation_admin;
GRANT ROLE  MYDB_STAGE_WAREHOUSE_DATA_HUB_ADMIN  TO ROLE mydb_STAGE_dw31_warehouse_admin;

-- DE Access to DEV env.
GRANT ROLE  MYDB_STAGE_RAW_DATA_HUB_R       TO ROLE DE_ELEVATED;
GRANT ROLE  MYDB_STAGE_CURATION_DATA_HUB_R  TO ROLE DE_ELEVATED;
GRANT ROLE  MYDB_STAGE_WAREHOUSE_DATA_HUB_R TO ROLE DE_ELEVATED;


-- Cross DB Permissions
GRANT ROLE  MYDB_STAGE_RAW_DATA_HUB_R                TO ROLE mydb_STAGE_dw31_curation_admin;
GRANT ROLE  MYDB_STAGE_CURATION_DATA_HUB_R           TO ROLE mydb_STAGE_dw31_warehouse_admin;

---- ENV: PROD
---- DATABASE: MYDB_PROD_RAW
USE ROLE ADMINISTRATOR;
CREATE SCHEMA IF NOT EXISTS MYDB_PROD_RAW.DATA_HUB;

USE ROLE SECURITYADMIN;
-- Create Schema Read Role
CREATE ROLE MYDB_PROD_RAW_DATA_HUB_R;
GRANT USAGE ON DATABASE MYDB_PROD_RAW TO ROLE MYDB_PROD_RAW_DATA_HUB_R;
GRANT USAGE ON SCHEMA MYDB_PROD_RAW.DATA_HUB TO ROLE MYDB_PROD_RAW_DATA_HUB_R;
GRANT USAGE ON SCHEMA MYDB_PROD_RAW.DATA_HUB TO ROLE PIPELINE_PROD_SVC_ACCESS;
GRANT SELECT ON FUTURE TABLES IN SCHEMA MYDB_PROD_RAW.DATA_HUB TO ROLE MYDB_PROD_RAW_DATA_HUB_R;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA MYDB_PROD_RAW.DATA_HUB TO ROLE MYDB_PROD_RAW_DATA_HUB_R;

-- Create Schema Write Role
CREATE ROLE MYDB_PROD_RAW_DATA_HUB_W;
GRANT ROLE MYDB_PROD_RAW_DATA_HUB_R TO ROLE MYDB_PROD_RAW_DATA_HUB_W;
GRANT DELETE, INSERT, UPDATE, TRUNCATE ON FUTURE TABLES IN SCHEMA MYDB_PROD_RAW.DATA_HUB TO ROLE MYDB_PROD_RAW_DATA_HUB_W;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA MYDB_PROD_RAW.DATA_HUB TO ROLE MYDB_PROD_RAW_DATA_HUB_W;      
--GRANT USAGE ON FUTURE INTEGRATIONS IN SCHEMA MYDB_PROD_RAW.DATA_HUB TO ROLE MYDB_PROD_RAW_DATA_HUB_W;    
GRANT MONITOR, OPERATE ON FUTURE PIPES IN SCHEMA MYDB_PROD_RAW.DATA_HUB TO ROLE MYDB_PROD_RAW_DATA_HUB_W;  
GRANT USAGE ON FUTURE STAGES IN SCHEMA MYDB_PROD_RAW.DATA_HUB TO ROLE MYDB_PROD_RAW_DATA_HUB_W;
GRANT SELECT ON FUTURE STREAMS IN SCHEMA MYDB_PROD_RAW.DATA_HUB TO ROLE MYDB_PROD_RAW_DATA_HUB_W;

-- Create Schema Admin Role
CREATE ROLE                              MYDB_PROD_RAW_DATA_HUB_ADMIN;
GRANT ROLE                               MYDB_PROD_RAW_DATA_HUB_W     TO ROLE MYDB_PROD_RAW_DATA_HUB_ADMIN;
GRANT ROLE                               MYDB_PROD_RAW_DATA_HUB_ADMIN TO ROLE SYSADMIN;
GRANT ROLE                               MYDB_PROD_RAW_DATA_HUB_ADMIN TO ROLE PIPELINE_PROD_SVC_ACCESS;     
GRANT CREATE FILE FORMAT ON SCHEMA       MYDB_PROD_RAW.DATA_HUB       TO ROLE MYDB_PROD_RAW_DATA_HUB_ADMIN;
GRANT CREATE MATERIALIZED VIEW ON SCHEMA MYDB_PROD_RAW.DATA_HUB       TO ROLE MYDB_PROD_RAW_DATA_HUB_ADMIN;
GRANT CREATE PIPE ON SCHEMA              MYDB_PROD_RAW.DATA_HUB       TO ROLE MYDB_PROD_RAW_DATA_HUB_ADMIN;
GRANT CREATE PROCEDURE ON SCHEMA         MYDB_PROD_RAW.DATA_HUB       TO ROLE MYDB_PROD_RAW_DATA_HUB_ADMIN;
GRANT CREATE SEQUENCE ON SCHEMA          MYDB_PROD_RAW.DATA_HUB       TO ROLE MYDB_PROD_RAW_DATA_HUB_ADMIN;
GRANT CREATE STAGE ON SCHEMA             MYDB_PROD_RAW.DATA_HUB       TO ROLE MYDB_PROD_RAW_DATA_HUB_ADMIN;
GRANT CREATE STREAM ON SCHEMA            MYDB_PROD_RAW.DATA_HUB       TO ROLE MYDB_PROD_RAW_DATA_HUB_ADMIN;
GRANT CREATE TABLE ON SCHEMA             MYDB_PROD_RAW.DATA_HUB       TO ROLE MYDB_PROD_RAW_DATA_HUB_ADMIN;
GRANT CREATE TAG ON SCHEMA               MYDB_PROD_RAW.DATA_HUB       TO ROLE MYDB_PROD_RAW_DATA_HUB_ADMIN;
GRANT CREATE TASK ON SCHEMA              MYDB_PROD_RAW.DATA_HUB       TO ROLE MYDB_PROD_RAW_DATA_HUB_ADMIN;
GRANT CREATE TEMPORARY TABLE ON SCHEMA   MYDB_PROD_RAW.DATA_HUB       TO ROLE MYDB_PROD_RAW_DATA_HUB_ADMIN;
GRANT CREATE VIEW ON SCHEMA              MYDB_PROD_RAW.DATA_HUB       TO ROLE MYDB_PROD_RAW_DATA_HUB_ADMIN;



-- Glue Access to env
GRANT ROLE  MYDB_PROD_RAW_DATA_HUB_ADMIN        TO ROLE mydb_PROD_dw31_raw_admin;
GRANT ROLE  MYDB_PROD_CURATION_DATA_HUB_ADMIN   TO ROLE mydb_PROD_dw31_curation_admin;
GRANT ROLE  MYDB_PROD_WAREHOUSE_DATA_HUB_ADMIN  TO ROLE mydb_PROD_dw31_warehouse_admin;

-- DE Access to DEV env.
GRANT ROLE  MYDB_PROD_RAW_DATA_HUB_R       TO ROLE DE_ELEVATED;
GRANT ROLE  MYDB_PROD_CURATION_DATA_HUB_R  TO ROLE DE_ELEVATED;
GRANT ROLE  MYDB_PROD_WAREHOUSE_DATA_HUB_R TO ROLE DE_ELEVATED;


-- Cross DB Permissions
GRANT ROLE  MYDB_PROD_RAW_DATA_HUB_R                TO ROLE mydb_PROD_dw31_curation_admin;
GRANT ROLE  MYDB_PROD_CURATION_DATA_HUB_R           TO ROLE mydb_PROD_dw31_warehouse_admin;