---- ENV: DEV
---- DATABASE: ULTRA_DEV_RAW
USE ROLE ADMINISTRATOR;
CREATE SCHEMA IF NOT EXISTS ULTRA_DEV_RAW.DATA_HUB;

USE ROLE SECURITYADMIN;
-- Create Schema Read Role
CREATE ROLE ULTRA_DEV_RAW_DATA_HUB_R;
GRANT USAGE ON DATABASE ULTRA_DEV_RAW TO ROLE ULTRA_DEV_RAW_DATA_HUB_R;
GRANT USAGE ON SCHEMA ULTRA_DEV_RAW.DATA_HUB TO ROLE ULTRA_DEV_RAW_DATA_HUB_R;
GRANT USAGE ON SCHEMA ULTRA_DEV_RAW.DATA_HUB TO ROLE PIPELINE_DEV_SVC_ACCESS;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ULTRA_DEV_RAW.DATA_HUB TO ROLE ULTRA_DEV_RAW_DATA_HUB_R;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ULTRA_DEV_RAW.DATA_HUB TO ROLE ULTRA_DEV_RAW_DATA_HUB_R;

-- Create Schema Write Role
CREATE ROLE ULTRA_DEV_RAW_DATA_HUB_W;
GRANT ROLE ULTRA_DEV_RAW_DATA_HUB_R TO ROLE ULTRA_DEV_RAW_DATA_HUB_W;
GRANT DELETE, INSERT, UPDATE, TRUNCATE ON FUTURE TABLES IN SCHEMA ULTRA_DEV_RAW.DATA_HUB TO ROLE ULTRA_DEV_RAW_DATA_HUB_W;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA ULTRA_DEV_RAW.DATA_HUB TO ROLE ULTRA_DEV_RAW_DATA_HUB_W;        
--GRANT USAGE ON FUTURE INTEGRATIONS IN SCHEMA ULTRA_DEV_RAW.DATA_HUB TO ROLE ULTRA_DEV_RAW_DATA_HUB_W;      
GRANT MONITOR, OPERATE ON FUTURE PIPES IN SCHEMA ULTRA_DEV_RAW.DATA_HUB TO ROLE ULTRA_DEV_RAW_DATA_HUB_W;    
GRANT USAGE ON FUTURE STAGES IN SCHEMA ULTRA_DEV_RAW.DATA_HUB TO ROLE ULTRA_DEV_RAW_DATA_HUB_W;
GRANT SELECT ON FUTURE STREAMS IN SCHEMA ULTRA_DEV_RAW.DATA_HUB TO ROLE ULTRA_DEV_RAW_DATA_HUB_W;

-- Create Schema Admin Role
CREATE ROLE                              ULTRA_DEV_RAW_DATA_HUB_ADMIN;
GRANT ROLE                               ULTRA_DEV_RAW_DATA_HUB_W     TO ROLE ULTRA_DEV_RAW_DATA_HUB_ADMIN;  
GRANT ROLE                               ULTRA_DEV_RAW_DATA_HUB_ADMIN TO ROLE SYSADMIN;
GRANT ROLE                               ULTRA_DEV_RAW_DATA_HUB_ADMIN TO ROLE PIPELINE_DEV_SVC_ACCESS;       
GRANT CREATE FILE FORMAT ON SCHEMA       ULTRA_DEV_RAW.DATA_HUB       TO ROLE ULTRA_DEV_RAW_DATA_HUB_ADMIN;  
GRANT CREATE MATERIALIZED VIEW ON SCHEMA ULTRA_DEV_RAW.DATA_HUB       TO ROLE ULTRA_DEV_RAW_DATA_HUB_ADMIN;  
GRANT CREATE PIPE ON SCHEMA              ULTRA_DEV_RAW.DATA_HUB       TO ROLE ULTRA_DEV_RAW_DATA_HUB_ADMIN;  
GRANT CREATE PROCEDURE ON SCHEMA         ULTRA_DEV_RAW.DATA_HUB       TO ROLE ULTRA_DEV_RAW_DATA_HUB_ADMIN;  
GRANT CREATE SEQUENCE ON SCHEMA          ULTRA_DEV_RAW.DATA_HUB       TO ROLE ULTRA_DEV_RAW_DATA_HUB_ADMIN;  
GRANT CREATE STAGE ON SCHEMA             ULTRA_DEV_RAW.DATA_HUB       TO ROLE ULTRA_DEV_RAW_DATA_HUB_ADMIN;  
GRANT CREATE STREAM ON SCHEMA            ULTRA_DEV_RAW.DATA_HUB       TO ROLE ULTRA_DEV_RAW_DATA_HUB_ADMIN;  
GRANT CREATE TABLE ON SCHEMA             ULTRA_DEV_RAW.DATA_HUB       TO ROLE ULTRA_DEV_RAW_DATA_HUB_ADMIN;  
GRANT CREATE TAG ON SCHEMA               ULTRA_DEV_RAW.DATA_HUB       TO ROLE ULTRA_DEV_RAW_DATA_HUB_ADMIN;  
GRANT CREATE TASK ON SCHEMA              ULTRA_DEV_RAW.DATA_HUB       TO ROLE ULTRA_DEV_RAW_DATA_HUB_ADMIN;  
GRANT CREATE TEMPORARY TABLE ON SCHEMA   ULTRA_DEV_RAW.DATA_HUB       TO ROLE ULTRA_DEV_RAW_DATA_HUB_ADMIN;  
GRANT CREATE VIEW ON SCHEMA              ULTRA_DEV_RAW.DATA_HUB       TO ROLE ULTRA_DEV_RAW_DATA_HUB_ADMIN;  



-- Glue Access to env
GRANT ROLE  ULTRA_DEV_RAW_DATA_HUB_ADMIN        TO ROLE ultra_DEV_dw31_raw_admin;


-- DE Access to DEV env.
GRANT ROLE  ULTRA_DEV_RAW_DATA_HUB_ADMIN       TO ROLE DE_ELEVATED;
GRANT ROLE  ULTRA_DEV_RAW_DATA_HUB_ADMIN       TO ROLE DE_COMMON;



-- DE Access to DEV env.
GRANT ROLE  ULTRA_DEV_RAW_DATA_HUB_ADMIN       TO ROLE DE_ELEVATED;
GRANT ROLE  ULTRA_DEV_RAW_DATA_HUB_ADMIN       TO ROLE DE_COMMON;


-- Cross DB Permissions
GRANT ROLE  ULTRA_DEV_RAW_DATA_HUB_R                TO ROLE ultra_DEV_dw31_curation_admin;
GRANT ROLE  ULTRA_DEV_CURATION_DATA_HUB_R           TO ROLE ultra_DEV_dw31_warehouse_admin;

---- ENV: STAGE
---- DATABASE: ULTRA_STAGE_RAW
USE ROLE ADMINISTRATOR;
CREATE SCHEMA IF NOT EXISTS ULTRA_STAGE_RAW.DATA_HUB;

USE ROLE SECURITYADMIN;
-- Create Schema Read Role
CREATE ROLE ULTRA_STAGE_RAW_DATA_HUB_R;
GRANT USAGE ON DATABASE ULTRA_STAGE_RAW TO ROLE ULTRA_STAGE_RAW_DATA_HUB_R;
GRANT USAGE ON SCHEMA ULTRA_STAGE_RAW.DATA_HUB TO ROLE ULTRA_STAGE_RAW_DATA_HUB_R;
GRANT USAGE ON SCHEMA ULTRA_STAGE_RAW.DATA_HUB TO ROLE PIPELINE_STAGE_SVC_ACCESS;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ULTRA_STAGE_RAW.DATA_HUB TO ROLE ULTRA_STAGE_RAW_DATA_HUB_R;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ULTRA_STAGE_RAW.DATA_HUB TO ROLE ULTRA_STAGE_RAW_DATA_HUB_R;

-- Create Schema Write Role
CREATE ROLE ULTRA_STAGE_RAW_DATA_HUB_W;
GRANT ROLE ULTRA_STAGE_RAW_DATA_HUB_R TO ROLE ULTRA_STAGE_RAW_DATA_HUB_W;
GRANT DELETE, INSERT, UPDATE, TRUNCATE ON FUTURE TABLES IN SCHEMA ULTRA_STAGE_RAW.DATA_HUB TO ROLE ULTRA_STAGE_RAW_DATA_HUB_W;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA ULTRA_STAGE_RAW.DATA_HUB TO ROLE ULTRA_STAGE_RAW_DATA_HUB_W;    
--GRANT USAGE ON FUTURE INTEGRATIONS IN SCHEMA ULTRA_STAGE_RAW.DATA_HUB TO ROLE ULTRA_STAGE_RAW_DATA_HUB_W;  
GRANT MONITOR, OPERATE ON FUTURE PIPES IN SCHEMA ULTRA_STAGE_RAW.DATA_HUB TO ROLE ULTRA_STAGE_RAW_DATA_HUB_W;
GRANT USAGE ON FUTURE STAGES IN SCHEMA ULTRA_STAGE_RAW.DATA_HUB TO ROLE ULTRA_STAGE_RAW_DATA_HUB_W;
GRANT SELECT ON FUTURE STREAMS IN SCHEMA ULTRA_STAGE_RAW.DATA_HUB TO ROLE ULTRA_STAGE_RAW_DATA_HUB_W;        

-- Create Schema Admin Role
CREATE ROLE                              ULTRA_STAGE_RAW_DATA_HUB_ADMIN;
GRANT ROLE                               ULTRA_STAGE_RAW_DATA_HUB_W     TO ROLE ULTRA_STAGE_RAW_DATA_HUB_ADMIN;
GRANT ROLE                               ULTRA_STAGE_RAW_DATA_HUB_ADMIN TO ROLE SYSADMIN;
GRANT ROLE                               ULTRA_STAGE_RAW_DATA_HUB_ADMIN TO ROLE PIPELINE_STAGE_SVC_ACCESS;   
GRANT CREATE FILE FORMAT ON SCHEMA       ULTRA_STAGE_RAW.DATA_HUB       TO ROLE ULTRA_STAGE_RAW_DATA_HUB_ADMIN;
GRANT CREATE MATERIALIZED VIEW ON SCHEMA ULTRA_STAGE_RAW.DATA_HUB       TO ROLE ULTRA_STAGE_RAW_DATA_HUB_ADMIN;
GRANT CREATE PIPE ON SCHEMA              ULTRA_STAGE_RAW.DATA_HUB       TO ROLE ULTRA_STAGE_RAW_DATA_HUB_ADMIN;
GRANT CREATE PROCEDURE ON SCHEMA         ULTRA_STAGE_RAW.DATA_HUB       TO ROLE ULTRA_STAGE_RAW_DATA_HUB_ADMIN;
GRANT CREATE SEQUENCE ON SCHEMA          ULTRA_STAGE_RAW.DATA_HUB       TO ROLE ULTRA_STAGE_RAW_DATA_HUB_ADMIN;
GRANT CREATE STAGE ON SCHEMA             ULTRA_STAGE_RAW.DATA_HUB       TO ROLE ULTRA_STAGE_RAW_DATA_HUB_ADMIN;
GRANT CREATE STREAM ON SCHEMA            ULTRA_STAGE_RAW.DATA_HUB       TO ROLE ULTRA_STAGE_RAW_DATA_HUB_ADMIN;
GRANT CREATE TABLE ON SCHEMA             ULTRA_STAGE_RAW.DATA_HUB       TO ROLE ULTRA_STAGE_RAW_DATA_HUB_ADMIN;
GRANT CREATE TAG ON SCHEMA               ULTRA_STAGE_RAW.DATA_HUB       TO ROLE ULTRA_STAGE_RAW_DATA_HUB_ADMIN;
GRANT CREATE TASK ON SCHEMA              ULTRA_STAGE_RAW.DATA_HUB       TO ROLE ULTRA_STAGE_RAW_DATA_HUB_ADMIN;
GRANT CREATE TEMPORARY TABLE ON SCHEMA   ULTRA_STAGE_RAW.DATA_HUB       TO ROLE ULTRA_STAGE_RAW_DATA_HUB_ADMIN;
GRANT CREATE VIEW ON SCHEMA              ULTRA_STAGE_RAW.DATA_HUB       TO ROLE ULTRA_STAGE_RAW_DATA_HUB_ADMIN;



-- Glue Access to env
GRANT ROLE  ULTRA_STAGE_RAW_DATA_HUB_ADMIN        TO ROLE ultra_STAGE_dw31_raw_admin;
GRANT ROLE  ULTRA_STAGE_CURATION_DATA_HUB_ADMIN   TO ROLE ultra_STAGE_dw31_curation_admin;
GRANT ROLE  ULTRA_STAGE_WAREHOUSE_DATA_HUB_ADMIN  TO ROLE ultra_STAGE_dw31_warehouse_admin;

-- DE Access to DEV env.
GRANT ROLE  ULTRA_STAGE_RAW_DATA_HUB_R       TO ROLE DE_ELEVATED;
GRANT ROLE  ULTRA_STAGE_CURATION_DATA_HUB_R  TO ROLE DE_ELEVATED;
GRANT ROLE  ULTRA_STAGE_WAREHOUSE_DATA_HUB_R TO ROLE DE_ELEVATED;


-- Cross DB Permissions
GRANT ROLE  ULTRA_STAGE_RAW_DATA_HUB_R                TO ROLE ultra_STAGE_dw31_curation_admin;
GRANT ROLE  ULTRA_STAGE_CURATION_DATA_HUB_R           TO ROLE ultra_STAGE_dw31_warehouse_admin;

---- ENV: PROD
---- DATABASE: ULTRA_PROD_RAW
USE ROLE ADMINISTRATOR;
CREATE SCHEMA IF NOT EXISTS ULTRA_PROD_RAW.DATA_HUB;

USE ROLE SECURITYADMIN;
-- Create Schema Read Role
CREATE ROLE ULTRA_PROD_RAW_DATA_HUB_R;
GRANT USAGE ON DATABASE ULTRA_PROD_RAW TO ROLE ULTRA_PROD_RAW_DATA_HUB_R;
GRANT USAGE ON SCHEMA ULTRA_PROD_RAW.DATA_HUB TO ROLE ULTRA_PROD_RAW_DATA_HUB_R;
GRANT USAGE ON SCHEMA ULTRA_PROD_RAW.DATA_HUB TO ROLE PIPELINE_PROD_SVC_ACCESS;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ULTRA_PROD_RAW.DATA_HUB TO ROLE ULTRA_PROD_RAW_DATA_HUB_R;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ULTRA_PROD_RAW.DATA_HUB TO ROLE ULTRA_PROD_RAW_DATA_HUB_R;

-- Create Schema Write Role
CREATE ROLE ULTRA_PROD_RAW_DATA_HUB_W;
GRANT ROLE ULTRA_PROD_RAW_DATA_HUB_R TO ROLE ULTRA_PROD_RAW_DATA_HUB_W;
GRANT DELETE, INSERT, UPDATE, TRUNCATE ON FUTURE TABLES IN SCHEMA ULTRA_PROD_RAW.DATA_HUB TO ROLE ULTRA_PROD_RAW_DATA_HUB_W;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA ULTRA_PROD_RAW.DATA_HUB TO ROLE ULTRA_PROD_RAW_DATA_HUB_W;      
--GRANT USAGE ON FUTURE INTEGRATIONS IN SCHEMA ULTRA_PROD_RAW.DATA_HUB TO ROLE ULTRA_PROD_RAW_DATA_HUB_W;    
GRANT MONITOR, OPERATE ON FUTURE PIPES IN SCHEMA ULTRA_PROD_RAW.DATA_HUB TO ROLE ULTRA_PROD_RAW_DATA_HUB_W;  
GRANT USAGE ON FUTURE STAGES IN SCHEMA ULTRA_PROD_RAW.DATA_HUB TO ROLE ULTRA_PROD_RAW_DATA_HUB_W;
GRANT SELECT ON FUTURE STREAMS IN SCHEMA ULTRA_PROD_RAW.DATA_HUB TO ROLE ULTRA_PROD_RAW_DATA_HUB_W;

-- Create Schema Admin Role
CREATE ROLE                              ULTRA_PROD_RAW_DATA_HUB_ADMIN;
GRANT ROLE                               ULTRA_PROD_RAW_DATA_HUB_W     TO ROLE ULTRA_PROD_RAW_DATA_HUB_ADMIN;
GRANT ROLE                               ULTRA_PROD_RAW_DATA_HUB_ADMIN TO ROLE SYSADMIN;
GRANT ROLE                               ULTRA_PROD_RAW_DATA_HUB_ADMIN TO ROLE PIPELINE_PROD_SVC_ACCESS;     
GRANT CREATE FILE FORMAT ON SCHEMA       ULTRA_PROD_RAW.DATA_HUB       TO ROLE ULTRA_PROD_RAW_DATA_HUB_ADMIN;
GRANT CREATE MATERIALIZED VIEW ON SCHEMA ULTRA_PROD_RAW.DATA_HUB       TO ROLE ULTRA_PROD_RAW_DATA_HUB_ADMIN;
GRANT CREATE PIPE ON SCHEMA              ULTRA_PROD_RAW.DATA_HUB       TO ROLE ULTRA_PROD_RAW_DATA_HUB_ADMIN;
GRANT CREATE PROCEDURE ON SCHEMA         ULTRA_PROD_RAW.DATA_HUB       TO ROLE ULTRA_PROD_RAW_DATA_HUB_ADMIN;
GRANT CREATE SEQUENCE ON SCHEMA          ULTRA_PROD_RAW.DATA_HUB       TO ROLE ULTRA_PROD_RAW_DATA_HUB_ADMIN;
GRANT CREATE STAGE ON SCHEMA             ULTRA_PROD_RAW.DATA_HUB       TO ROLE ULTRA_PROD_RAW_DATA_HUB_ADMIN;
GRANT CREATE STREAM ON SCHEMA            ULTRA_PROD_RAW.DATA_HUB       TO ROLE ULTRA_PROD_RAW_DATA_HUB_ADMIN;
GRANT CREATE TABLE ON SCHEMA             ULTRA_PROD_RAW.DATA_HUB       TO ROLE ULTRA_PROD_RAW_DATA_HUB_ADMIN;
GRANT CREATE TAG ON SCHEMA               ULTRA_PROD_RAW.DATA_HUB       TO ROLE ULTRA_PROD_RAW_DATA_HUB_ADMIN;
GRANT CREATE TASK ON SCHEMA              ULTRA_PROD_RAW.DATA_HUB       TO ROLE ULTRA_PROD_RAW_DATA_HUB_ADMIN;
GRANT CREATE TEMPORARY TABLE ON SCHEMA   ULTRA_PROD_RAW.DATA_HUB       TO ROLE ULTRA_PROD_RAW_DATA_HUB_ADMIN;
GRANT CREATE VIEW ON SCHEMA              ULTRA_PROD_RAW.DATA_HUB       TO ROLE ULTRA_PROD_RAW_DATA_HUB_ADMIN;



-- Glue Access to env
GRANT ROLE  ULTRA_PROD_RAW_DATA_HUB_ADMIN        TO ROLE ultra_PROD_dw31_raw_admin;
GRANT ROLE  ULTRA_PROD_CURATION_DATA_HUB_ADMIN   TO ROLE ultra_PROD_dw31_curation_admin;
GRANT ROLE  ULTRA_PROD_WAREHOUSE_DATA_HUB_ADMIN  TO ROLE ultra_PROD_dw31_warehouse_admin;

-- DE Access to DEV env.
GRANT ROLE  ULTRA_PROD_RAW_DATA_HUB_R       TO ROLE DE_ELEVATED;
GRANT ROLE  ULTRA_PROD_CURATION_DATA_HUB_R  TO ROLE DE_ELEVATED;
GRANT ROLE  ULTRA_PROD_WAREHOUSE_DATA_HUB_R TO ROLE DE_ELEVATED;


-- Cross DB Permissions
GRANT ROLE  ULTRA_PROD_RAW_DATA_HUB_R                TO ROLE ultra_PROD_dw31_curation_admin;
GRANT ROLE  ULTRA_PROD_CURATION_DATA_HUB_R           TO ROLE ultra_PROD_dw31_warehouse_admin;