---- ENV: DEV
---- DATABASE: DEV_RAW
USE ROLE ADMINISTRATOR;
CREATE SCHEMA IF NOT EXISTS DEV_RAW.DATA_HUB;

USE ROLE SECURITYADMIN;
-- Create Schema Read Role
CREATE ROLE DATA_HUB_R;
GRANT USAGE ON DATABASE DEV_RAW TO ROLE DATA_HUB_R;
GRANT USAGE ON SCHEMA DEV_RAW.DATA_HUB TO ROLE DATA_HUB_R;
GRANT USAGE ON SCHEMA DEV_RAW.DATA_HUB TO ROLE PIPELINE_DEV_SVC_ACCESS;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DEV_RAW.DATA_HUB TO ROLE DATA_HUB_R;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA DEV_RAW.DATA_HUB TO ROLE DATA_HUB_R;

-- Create Schema Write Role
CREATE ROLE DATA_HUB_W;
GRANT ROLE DATA_HUB_R TO ROLE DATA_HUB_W;
GRANT DELETE, INSERT, UPDATE, TRUNCATE ON FUTURE TABLES IN SCHEMA DEV_RAW.DATA_HUB TO ROLE DATA_HUB_W;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA DEV_RAW.DATA_HUB TO ROLE DATA_HUB_W;        
--GRANT USAGE ON FUTURE INTEGRATIONS IN SCHEMA DEV_RAW.DATA_HUB TO ROLE DATA_HUB_W;      
GRANT MONITOR, OPERATE ON FUTURE PIPES IN SCHEMA DEV_RAW.DATA_HUB TO ROLE DATA_HUB_W;    
GRANT USAGE ON FUTURE STAGES IN SCHEMA DEV_RAW.DATA_HUB TO ROLE DATA_HUB_W;
GRANT SELECT ON FUTURE STREAMS IN SCHEMA DEV_RAW.DATA_HUB TO ROLE DATA_HUB_W;

-- Create Schema Admin Role
CREATE ROLE                              DATA_HUB_ADMIN;
GRANT ROLE                               DATA_HUB_W     TO ROLE DATA_HUB_ADMIN;  
GRANT ROLE                               DATA_HUB_ADMIN TO ROLE SYSADMIN;
GRANT ROLE                               DATA_HUB_ADMIN TO ROLE PIPELINE_DEV_SVC_ACCESS;       
GRANT CREATE FILE FORMAT ON SCHEMA       DEV_RAW.DATA_HUB       TO ROLE DATA_HUB_ADMIN;  
GRANT CREATE MATERIALIZED VIEW ON SCHEMA DEV_RAW.DATA_HUB       TO ROLE DATA_HUB_ADMIN;  
GRANT CREATE PIPE ON SCHEMA              DEV_RAW.DATA_HUB       TO ROLE DATA_HUB_ADMIN;  
GRANT CREATE PROCEDURE ON SCHEMA         DEV_RAW.DATA_HUB       TO ROLE DATA_HUB_ADMIN;  
GRANT CREATE SEQUENCE ON SCHEMA          DEV_RAW.DATA_HUB       TO ROLE DATA_HUB_ADMIN;  
GRANT CREATE STAGE ON SCHEMA             DEV_RAW.DATA_HUB       TO ROLE DATA_HUB_ADMIN;  
GRANT CREATE STREAM ON SCHEMA            DEV_RAW.DATA_HUB       TO ROLE DATA_HUB_ADMIN;  
GRANT CREATE TABLE ON SCHEMA             DEV_RAW.DATA_HUB       TO ROLE DATA_HUB_ADMIN;  
GRANT CREATE TAG ON SCHEMA               DEV_RAW.DATA_HUB       TO ROLE DATA_HUB_ADMIN;  
GRANT CREATE TASK ON SCHEMA              DEV_RAW.DATA_HUB       TO ROLE DATA_HUB_ADMIN;  
GRANT CREATE TEMPORARY TABLE ON SCHEMA   DEV_RAW.DATA_HUB       TO ROLE DATA_HUB_ADMIN;  
GRANT CREATE VIEW ON SCHEMA              DEV_RAW.DATA_HUB       TO ROLE DATA_HUB_ADMIN; 



-- DE Access to DEV env.
GRANT ROLE  DATA_HUB_ADMIN       TO ROLE DE_ELEVATED;
GRANT ROLE  DATA_HUB_ADMIN       TO ROLE DE_COMMON;