---- ENV: STAGE
---- DATABASE: SOURCEDATA_TEST
USE ROLE ADMINISTRATOR;
CREATE SCHEMA IF NOT EXISTS SOURCEDATA_TEST.DATA_HUB;

USE ROLE SECURITYADMIN;
-- Create Schema Read Role
CREATE ROLE SOURCEDATA_TEST_DATA_HUB_R;
GRANT USAGE ON DATABASE SOURCEDATA_TEST TO ROLE DATAENGINEERUSER;
GRANT USAGE ON SCHEMA SOURCEDATA_TEST.DATA_HUB TO ROLE DATAENGINEERUSER;
GRANT USAGE ON SCHEMA SOURCEDATA_TEST.DATA_HUB TO ROLE DATAENGINEERUSER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SOURCEDATA_TEST.DATA_HUB TO ROLE DATAENGINEERUSER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA SOURCEDATA_TEST.DATA_HUB TO ROLE DATAENGINEERUSER;

-- Create Schema Write Role
CREATE ROLE SOURCEDATA_TEST_DATA_HUB_W;
GRANT ROLE SOURCEDATA_TEST_DATA_HUB_R TO ROLE DATAENGINEERUSER;
GRANT DELETE, INSERT, UPDATE, TRUNCATE ON FUTURE TABLES IN SCHEMA SOURCEDATA_TEST.DATA_HUB TO ROLE DATAENGINEERUSER;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA SOURCEDATA_TEST.DATA_HUB TO ROLE DATAENGINEERUSER;
--GRANT USAGE ON FUTURE INTEGRATIONS IN SCHEMA SOURCEDATA_TEST.DATA_HUB TO ROLE DATAENGINEERUSER;
GRANT MONITOR, OPERATE ON FUTURE PIPES IN SCHEMA SOURCEDATA_TEST.DATA_HUB TO ROLE DATAENGINEERUSER;
GRANT USAGE ON FUTURE STAGES IN SCHEMA SOURCEDATA_TEST.DATA_HUB TO ROLE DATAENGINEERUSER;
GRANT SELECT ON FUTURE STREAMS IN SCHEMA SOURCEDATA_TEST.DATA_HUB TO ROLE DATAENGINEERUSER;

-- Create Schema Admin Role
CREATE ROLE                              SOURCEDATA_TEST_DATA_HUB_ADMIN;
GRANT ROLE                               SOURCEDATA_TEST_DATA_HUB_W     TO ROLE DATAENGINEERUSER;
GRANT ROLE                               SOURCEDATA_TEST_DATA_HUB_ADMIN TO ROLE DATAENGINEERUSER;
GRANT ROLE                               SOURCEDATA_TEST_DATA_HUB_ADMIN TO ROLE DATAENGINEERUSER;
GRANT CREATE FILE FORMAT ON SCHEMA       SOURCEDATA_TEST.DATA_HUB       TO ROLE DATAENGINEERUSER;
GRANT CREATE MATERIALIZED VIEW ON SCHEMA SOURCEDATA_TEST.DATA_HUB       TO ROLE DATAENGINEERUSER;
GRANT CREATE PIPE ON SCHEMA              SOURCEDATA_TEST.DATA_HUB       TO ROLE DATAENGINEERUSER;
GRANT CREATE PROCEDURE ON SCHEMA         SOURCEDATA_TEST.DATA_HUB       TO ROLE DATAENGINEERUSER;
GRANT CREATE SEQUENCE ON SCHEMA          SOURCEDATA_TEST.DATA_HUB       TO ROLE DATAENGINEERUSER;
GRANT CREATE STAGE ON SCHEMA             SOURCEDATA_TEST.DATA_HUB       TO ROLE DATAENGINEERUSER;
GRANT CREATE STREAM ON SCHEMA            SOURCEDATA_TEST.DATA_HUB       TO ROLE DATAENGINEERUSER;
GRANT CREATE TABLE ON SCHEMA             SOURCEDATA_TEST.DATA_HUB       TO ROLE DATAENGINEERUSER;
GRANT CREATE TAG ON SCHEMA               SOURCEDATA_TEST.DATA_HUB       TO ROLE DATAENGINEERUSER;
GRANT CREATE TASK ON SCHEMA              SOURCEDATA_TEST.DATA_HUB       TO ROLE DATAENGINEERUSER;
GRANT CREATE TEMPORARY TABLE ON SCHEMA   SOURCEDATA_TEST.DATA_HUB       TO ROLE DATAENGINEERUSER;
GRANT CREATE VIEW ON SCHEMA              SOURCEDATA_TEST.DATA_HUB       TO ROLE DATAENGINEERUSER;

-- Glue Access to env
GRANT ROLE SOURCEDATA_TEST_DATA_HUB_ADMIN        TO ROLE DATAENGINEERUSER;
GRANT ROLE MYDB_STAGE_CURATION_DATA_HUB_ADMIN    TO ROLE DATAENGINEERUSER;
GRANT ROLE MYDB_STAGE_WAREHOUSE_DATA_HUB_ADMIN   TO ROLE DATAENGINEERUSER;

-- DE Access to DEV env.
GRANT ROLE SOURCEDATA_TEST_DATA_HUB_R            TO ROLE DATAENGINEERUSER;
GRANT ROLE MYDB_STAGE_CURATION_DATA_HUB_R        TO ROLE DATAENGINEERUSER;
GRANT ROLE MYDB_STAGE_WAREHOUSE_DATA_HUB_R       TO ROLE DATAENGINEERUSER;

-- Cross DB Permissions
GRANT ROLE SOURCEDATA_TEST_DATA_HUB_R            TO ROLE DATAENGINEERUSER;
GRANT ROLE MYDB_STAGE_CURATION_DATA_HUB_R        TO ROLE DATAENGINEERUSER;
