

-- ************************** SqlDBM: Snowflake *************************
-- ********** Generated by SqlDBM: DATA_HUB by MY_EMAIL_ADDRESS@example.com **********


-- ************************************** DATA_HUB.REF_TriggerType
CREATE OR REPLACE TABLE DATA_HUB.REF_Trigger_Type
(
 TriggerTypeCode varchar(25) NOT NULL,
 TriggerTypeId   integer NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 TriggerTypeName varchar(255) NOT NULL,
 TriggerTypeDesc varchar(255) NOT NULL,
 CreatedBy       varchar(255) NOT NULL,
 CreatedDtm      date NOT NULL,
 ModifiedBy      varchar(255),
 ModifiedDtm     date,

 CONSTRAINT PK_RefTriggerType_TriggerTypeCode PRIMARY KEY ( TriggerTypeCode )
);



-- ************************************** DATA_HUB.REF_TransferMethod
CREATE OR REPLACE TABLE DATA_HUB.REF_Transfer_Method
(
 TransferMethodId   integer NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 TransferMethodCode varchar(25) NOT NULL,
 TransferMethodName varchar(255) NOT NULL,
 TransferMethodDesc varchar(255) NOT NULL,
 CreatedBy          varchar(255) NOT NULL,
 CreatedDtm         date NOT NULL,
 ModifiedBy         varchar(255),
 ModifiedDtm        date,

 CONSTRAINT PK_RefTransferMethod__MethodCode PRIMARY KEY ( TransferMethodCode )
);

-- ************************************** DATA_HUB.REF_StorageMethod
CREATE OR REPLACE TABLE DATA_HUB.REF_Storage_Method
(
 StorageMethodId   integer NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 StorageMethodCode varchar(25) NOT NULL,
 StorageMethodName varchar(255) NOT NULL,
 StorageMethodDesc varchar(255) NOT NULL,
 CreatedBy         varchar(255) NOT NULL,
 CreatedDtm        date NOT NULL,
 ModifiedBy        varchar(255),
 ModifiedDtm       date,

 CONSTRAINT PK_RefStorageMethod__MethodCode PRIMARY KEY ( StorageMethodCode )
);


-- ************************************** DATA_HUB.REF_Status
CREATE OR REPLACE TABLE DATA_HUB.REF_Status
(
 StatusId    integer NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 StatusCode  varchar(25) NOT NULL,
 StatusName  varchar(255) NOT NULL,
 StatusDesc  varchar(255) NOT NULL,
 StatusType  varchar(255) NOT NULL,
 CreatedBy   varchar(255) NOT NULL,
 CreatedDtm  date NOT NULL,
 ModifiedBy  varchar(255),
 ModifiedDtm date,

 CONSTRAINT PK_RefStatus__StatusCode PRIMARY KEY ( StatusCode )
 --CONSTRAINT UNQ_RefStatus__StatusCode UNIQUE ( StatusCode )
);

-- ************************************** DATA_HUB.REF_Method
CREATE OR REPLACE TABLE DATA_HUB.REF_Method
(
 MethodCode  varchar(25) NOT NULL,
 MethodId    integer NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 MethodName  varchar(255),
 MethodDesc  varchar(255),
 CreatedBy   varchar(255) NOT NULL,
 CreatedDtm  date NOT NULL,
 ModifiedBy  varchar(255),
 ModifiedDtm date,

 CONSTRAINT PK_RefMethod_MethodCode PRIMARY KEY ( MethodCode )
);

-- ************************************** DATA_HUB.REF_Interval
CREATE OR REPLACE TABLE DATA_HUB.REF_Interval
(
 IntervalCode varchar(25) NOT NULL,
 IntervalId   integer NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 IntervalName varchar(255),
 IntervalDesc varchar(255),
 SLAFormat    varchar(255),
 SLARegEx     varchar(255),
 CreatedBy    varchar(255) NOT NULL,
 CreatedDtm   date NOT NULL,
 ModifiedBy   varchar(255),
 ModifiedDtm  date,

 CONSTRAINT PK_RefInterval_IntervalCode PRIMARY KEY ( IntervalCode )
);



-- ************************************** DATA_HUB.REF_Interface
CREATE OR REPLACE TABLE DATA_HUB.REF_Interface
(
 InterfaceCode varchar(25) NOT NULL,
 InterfaceId   integer NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 InterfaceName varchar(255),
 InterfaceDesc varchar(255) NOT NULL,
 CreatedBy     varchar(255) NOT NULL,
 CreatedDtm    date NOT NULL,
 ModifiedBy    varchar(255),
 ModifiedDtm   date,

 CONSTRAINT PK_RefInterface__InterfaceCode PRIMARY KEY ( InterfaceCode )
);

-- ************************************** DATA_HUB.REF_FileFormat
CREATE OR REPLACE TABLE DATA_HUB.REF_File_Format
(
 FileFormatCode   varchar(25) NOT NULL,
 FileFormatId     integer NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 FileFormatName   varchar(255) NOT NULL,
 FileFormatDesc   varchar(255) NOT NULL,
 FileExtension    varchar(255) NOT NULL,
 DotFileExtension varchar(255) NOT NULL,
 CreatedBy        varchar(255) NOT NULL,
 CreatedDtm       date NOT NULL,
 ModifiedBy       varchar(255),
 ModifiedDtm      date,

 CONSTRAINT PK_RefFileFormat_FileFormatCode PRIMARY KEY ( FileFormatCode )
);



-- ************************************** DATA_HUB.Contact
CREATE OR REPLACE TABLE DATA_HUB.Contact
(
 ContactId   integer NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 CompanyName varchar(255) NOT NULL,
 ContactName varchar(255) NOT NULL DEFAULT ('N/A'),
 Tier        varchar(255),
 Email       varchar(255),
 Phone       varchar(255),
 SupportURL  varchar(255),
 Address01   varchar(255),
 Address02   varchar(255),
 City        varchar(255),
 State       varchar(255),
 ZipCode     varchar(255),
 CreatedBy   varchar(255) NOT NULL,
 CreatedDtm  date NOT NULL,
 ModifiedBy  varchar(255),
 ModifiedDtm date,

 CONSTRAINT PK_ContactContactId PRIMARY KEY ( ContactId ),
 CONSTRAINT UNQ_Contact__Name UNIQUE ( ContactName )
);

-- ************************************** DATA_HUB.Publisher
CREATE OR REPLACE TABLE DATA_HUB.Publisher
(
 PublisherId            integer NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 ContactId              integer NOT NULL,
 PublisherCode          varchar(25) NOT NULL,
 PublisherName          varchar(255) NOT NULL,
 PublisherDesc          varchar(255),
 InterfaceCode          varchar(25) NOT NULL DEFAULT (('N/A')),
 SecretKey              varchar(255),
 CreatedBy              varchar(255) NOT NULL,
 CreatedDtm             date NOT NULL,
 ModifiedBy             varchar(255),
 ModifiedDtm            date,

 CONSTRAINT PK_PubrPublisherId PRIMARY KEY ( PublisherId ),
 CONSTRAINT UNQ_Publisher__PublisherCode UNIQUE ( PublisherCode ),
 CONSTRAINT FK_Publisher_RefInterface__InterfaceCode FOREIGN KEY ( InterfaceCode ) REFERENCES DATA_HUB.REF_Interface ( InterfaceCode ),
 CONSTRAINT FK_RefContact__ContactId FOREIGN KEY ( ContactId ) REFERENCES DATA_HUB.Contact ( ContactId )
);

-- ************************************** DATA_HUB.Subscriber
CREATE OR REPLACE TABLE DATA_HUB.Subscriber
(
 SubscriberId           integer NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 ContactId              integer NOT NULL,
 SubscriberCode         varchar(25) NOT NULL,
 SubscriberName         varchar(255) NOT NULL,
 SubscriberDesc         varchar(255),
 InterfaceCode          varchar(25) NOT NULL DEFAULT (('N/A')),
 SecretKey              varchar(255),
 /*
 SiteURL                varchar(255),
 SiteUser               varchar(255),
 SitePassword           binary(8388608),
 SiteHostKeyFingerprint binary(8388608),
 SitePort               varchar(255),
 SiteProtocol           varchar(255),
 PrivateKeyPassPhrase   binary(8388608),
 PrivateKeyFile         binary(8388608),
 */
 NotificationHostName   varchar(255) NOT NULL DEFAULT (('N/A')),
 NotificationInstance   varchar(255) NOT NULL DEFAULT (('N/A')),
 NotificationDatabase   varchar(255) NOT NULL DEFAULT (('N/A')),
 NotificationSchema     varchar(255) NOT NULL DEFAULT (('N/A')),
 NotificationProcedure  varchar(255) NOT NULL DEFAULT (('N/A')),
 NotificationURI        varchar(255) NOT NULL DEFAULT (('N/A')),
 NotificationTopic      varchar(255) NOT NULL DEFAULT (('N/A')),
 CreatedBy              varchar(255) NOT NULL,
 CreatedDtm             date,
 ModifiedBy             varchar(255),
 ModifiedDtm            date,

 CONSTRAINT PK_Subcriber__SubscriberId PRIMARY KEY ( SubscriberId ),
 CONSTRAINT UNQ_Subscriber__SubscriberCode UNIQUE ( SubscriberCode ),
 CONSTRAINT FK_Subscriber_RefInterface__InterfaceCode FOREIGN KEY ( InterfaceCode ) REFERENCES DATA_HUB.REF_Interface ( InterfaceCode )
);



-- ************************************** DATA_HUB.Subscription
CREATE OR REPLACE TABLE DATA_HUB.Subscription
(
 SubscriptionId          integer NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 PublicationCode         varchar(25) NOT NULL,
 SubscriberCode          varchar(25) NOT NULL,
 SubscriptionCode        varchar(25) NOT NULL,
 SubscriptionName        varchar(255) NOT NULL,
 SubscriptionDesc        varchar(255),
 InterfaceCode           varchar(25) NOT NULL,
 IsActive                integer NOT NULL DEFAULT ((1)),
 SubscriptionFilePath    varchar(255),
 SubscriptionArchivePath varchar(255),
 SrcFilePath             varchar(255),
 DestTableName           varchar(255),
 DestFileFormatCode      varchar(25),
 CreatedBy               varchar(255) NOT NULL,
 CreatedDtm              date NOT NULL,
 ModifiedBy              varchar(255),
 ModifiedDtm             date,

 CONSTRAINT PK_Subscription__SubscriptionId PRIMARY KEY ( SubscriptionId ),
 CONSTRAINT UNQ_Subscription__SubscriptionCode UNIQUE ( SubscriptionCode ),
 CONSTRAINT FK_FileFormat_Subscription__FileFormatCode FOREIGN KEY ( DestFileFormatCode ) REFERENCES DATA_HUB.REF_File_Format ( FileFormatCode ),
 CONSTRAINT FK_Interface_Subscription__InterfaceCode FOREIGN KEY ( InterfaceCode ) REFERENCES DATA_HUB.REF_Interface ( InterfaceCode ),
 CONSTRAINT FK_Subscriber_Subscription__SubscriberId FOREIGN KEY ( SubscriberCode ) REFERENCES DATA_HUB.Subscriber ( SubscriberCode )
);

-- ************************************** DATA_HUB.Publication
CREATE OR REPLACE TABLE DATA_HUB.Publication
(
 PublicationId            integer NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 PublisherId              integer NOT NULL,
 PublisherCode            varchar(25) NOT NULL,
 PublicationCode          varchar(25) NOT NULL,
 PublicationName          varchar(255) NOT NULL,
 PublicationDesc          varchar(255) NOT NULL,
 SrcPublicationCode       varchar(255) NOT NULL DEFAULT 'UNK',
 SrcPublicationName       varchar(255),
 PublicationEntity        varchar(255) NOT NULL,
 PublicationBucket        varchar(255) NOT NULL,
 PublicationFilePath      varchar(255),
 PublicationArchivePath   varchar(255),
 SrcFilePath              varchar(255),
 SrcFileRegEx             varchar(255) NOT NULL DEFAULT 'N/A',
 SrcDeltaAttributes       varchar(255) NOT NULL DEFAULT 'N/A',
 DestTableName            varchar(255),
 SrcFileFormatCode        varchar(255) NOT NULL DEFAULT 'UNK',
 StandardFileRegEx        varchar(255) NOT NULL DEFAULT 'UNK',
 StandardFileFormatCode   varchar(25) NOT NULL DEFAULT 'UNK',
 ProcessingMethodCode     varchar(25) NOT NULL DEFAULT 'UNK',
 TransferMethodCode       varchar(25) NOT NULL DEFAULT 'UNK',
 StorageMethodCode        varchar(25) NOT NULL DEFAULT 'UNK',
 IntervalCode             varchar(25) NOT NULL DEFAULT 'UNK',
 /*
 StageJobName             varchar(255) NOT NULL DEFAULT 'N/A',
 SSISFolder               varchar(255) NOT NULL DEFAULT 'N/A',
 SSISProject              varchar(255) NOT NULL DEFAULT 'N/A',
 SSISPackage              varchar(255) NOT NULL DEFAULT 'N/A',
 DataFactoryName          varchar(255) NOT NULL DEFAULT 'N/A',
 DataFactoryPipeline      varchar(255) NOT NULL DEFAULT 'N/A',
 */

 
 IntervalLength           integer NOT NULL DEFAULT 0,
 SLATime                  varchar(255),
 SLAEndTimeInMinutes      integer,
 NextExecutionDtm         date NOT NULL DEFAULT CURRENT_DATE,
 TriggerTypeCode          varchar(255) NOT NULL DEFAULT 'N/A',
 IsActive                 boolean NOT NULL DEFAULT True,
 IsDataHub                boolean NOT NULL DEFAULT True,
 Bound                    varchar(255) NOT NULL DEFAULT 'In',
 RetryMax                 integer NOT NULL DEFAULT 0,
 RetryIntervalCode        varchar(255) NOT NULL DEFAULT 'UNK',
 RetryIntervalLength      integer NOT NULL DEFAULT 0,
 PublicationGroupSequence integer NOT NULL DEFAULT 1,
 PublicationGroupDesc     varchar(255) NOT NULL DEFAULT 'Default',
 KeyStoreName             varchar(255) NOT NULL DEFAULT 'N/A',
 GlueWorkflow             varchar(255) NOT NULL DEFAULT 'N/A',
 AirFlowDAG               varchar(255) NOT NULL DEFAULT 'N/A',
 CreatedBy                varchar(255) NOT NULL,
 CreatedDtm               date NOT NULL,
 ModifiedBy               varchar(255),
 ModifiedDtm              date,

 CONSTRAINT PK_PubnPublisherCode PRIMARY KEY ( PublicationCode )
 --CONSTRAINT UNQ_Publication__PublicationCode UNIQUE ( PublicationCode ),
 --CONSTRAINT FK_FeedFormat_Publication__FeedFormatCode FOREIGN KEY ( SrcFileFormatCode ) REFERENCES DATA_HUB.REF_FileFormat ( FileFormatCode ),
 --CONSTRAINT FK_Interval_Publication__IntervalCode FOREIGN KEY ( IntervalCode ) REFERENCES DATA_HUB.REF_Interval ( IntervalCode ),
 --CONSTRAINT FK_Interval_Publication__RetryIntervalCode FOREIGN KEY ( RetryIntervalCode ) REFERENCES DATA_HUB.REF_Interval ( IntervalCode ),
 --CONSTRAINT FK_Method_Publication__StorageMethodCode FOREIGN KEY ( StorageMethodCode ) REFERENCES DATA_HUB.REF_Storage_Method ( StorageMethodCode ),
 --CONSTRAINT FK_Method_Publication__TransferMethodCode FOREIGN KEY ( TransferMethodCode ) REFERENCES DATA_HUB.REF_Transfer_Method ( TransferMethodCode ),
 --CONSTRAINT FK_PubnPublisherId FOREIGN KEY ( PublisherCode ) REFERENCES DATA_HUB.Publisher ( PublisherCode ),
 --CONSTRAINT FK_StandardizedFileFormat_Publication__FeedFormatCode FOREIGN KEY ( StandardFileFormatCode ) REFERENCES DATA_HUB.REF_FileFormat ( FileFormatCode ),
 --CONSTRAINT FK_TriggerType_Publication__TriggerTypeCode FOREIGN KEY ( TriggerTypeCode ) REFERENCES DATA_HUB.REF_Trigger_Type ( TriggerTypeCode )
);

-- ************************************** DATA_HUB."Issue"
CREATE OR REPLACE TABLE DATA_HUB.ISSUE
(
 IssueId             bigint NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
-- PublicationId       integer NOT NULL,
 PublicationCode     varchar(25) NOT NULL,
 StatusCode          varchar(25) NOT NULL,
 ReportDate          date NOT NULL,
 SrcDFPublisherId    varchar(255),
 SrcDFPublicationId  varchar(255),
 SrcDFIssueId        varchar(255),
 SrcIssueName        varchar(255),
 SrcDFCreatedDate    date,
 DataLakePath        varchar(255) NOT NULL DEFAULT '/Raw Data Zone/...',
 IssueName           varchar(255) NOT NULL,
 PublicationSeq      integer NOT NULL DEFAULT -1,
 DailyPublicationSeq integer NOT NULL DEFAULT -1,
 FirstRecordSeq      integer,
 LastRecordSeq       integer,
 FirstRecordChecksum varchar(255),
 LastRecordChecksum  varchar(255),
 PeriodStartTime     TIMESTAMP_TZ  NOT NULL,
 PeriodEndTime       TIMESTAMP_TZ ,
 PeriodStartTimeUTC  TIMESTAMP_TZ ,
 PeriodEndTimeUTC    TIMESTAMP_TZ ,
 IssueConsumedDate   TIMESTAMP_TZ,
 RecordCount         integer NOT NULL,
 RetryCount          integer NOT NULL DEFAULT 0,
 ETLExecutionId      varchar(255),
 CreatedBy           varchar(255) NOT NULL,
 CreatedDtm          TIMESTAMP_TZ NOT NULL,
 ModifiedBy          varchar(255),
 ModifiedDtm         TIMESTAMP_TZ,

 CONSTRAINT Pk_IssueIssueId PRIMARY KEY ( IssueId ),
 CONSTRAINT FK_Issue__Publication__PublicationCode FOREIGN KEY ( PublicationCode ) REFERENCES DATA_HUB.Publication ( PublicationCode ),
 CONSTRAINT FK_Issue__RefStatus__StatusCode FOREIGN KEY ( StatusCode ) REFERENCES DATA_HUB.REF_Status ( StatusCode )
);



GRANT OWNERSHIP ON TABLE MY_ORG_@ENV@_RAW.DATA_HUB.REF_Trigger_Type TO ROLE MY_ORG_@ENV@_RAW_DATA_HUB_ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON TABLE MY_ORG_@ENV@_RAW.DATA_HUB.REF_Transfer_Method TO ROLE MY_ORG_@ENV@_RAW_DATA_HUB_ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON TABLE MY_ORG_@ENV@_RAW.DATA_HUB.REF_Storage_Method TO ROLE MY_ORG_@ENV@_RAW_DATA_HUB_ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON TABLE MY_ORG_@ENV@_RAW.DATA_HUB.REF_Status TO ROLE MY_ORG_@ENV@_RAW_DATA_HUB_ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON TABLE MY_ORG_@ENV@_RAW.DATA_HUB.REF_Method TO ROLE MY_ORG_@ENV@_RAW_DATA_HUB_ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON TABLE MY_ORG_@ENV@_RAW.DATA_HUB.REF_Interval TO ROLE MY_ORG_@ENV@_RAW_DATA_HUB_ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON TABLE MY_ORG_@ENV@_RAW.DATA_HUB.REF_Interface TO ROLE MY_ORG_@ENV@_RAW_DATA_HUB_ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON TABLE MY_ORG_@ENV@_RAW.DATA_HUB.REF_File_Format TO ROLE MY_ORG_@ENV@_RAW_DATA_HUB_ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON TABLE MY_ORG_@ENV@_RAW.DATA_HUB.Contact TO ROLE MY_ORG_@ENV@_RAW_DATA_HUB_ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON TABLE MY_ORG_@ENV@_RAW.DATA_HUB.Publisher TO ROLE MY_ORG_@ENV@_RAW_DATA_HUB_ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON TABLE MY_ORG_@ENV@_RAW.DATA_HUB.Publication TO ROLE MY_ORG_@ENV@_RAW_DATA_HUB_ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON TABLE MY_ORG_@ENV@_RAW.DATA_HUB.Subscriber TO ROLE MY_ORG_@ENV@_RAW_DATA_HUB_ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON TABLE MY_ORG_@ENV@_RAW.DATA_HUB.Subscription TO ROLE MY_ORG_@ENV@_RAW_DATA_HUB_ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON TABLE MY_ORG_@ENV@_RAW.DATA_HUB.Issue TO ROLE MY_ORG_@ENV@_RAW_DATA_HUB_ADMIN COPY CURRENT GRANTS;
